### ISSUE TITLE
 Portal Runner (NTSC-U): Various graphical regressions.

### ISSUE THREAD

**Issue by Yui12** [PCSX2/pcsx2#1017]
Specs: Windows 7 Pro
Intel Core I3-3220
Geforce GT 640 (Updated Drivers)
8GB RAM
Default plugins, default settings, speedhacks, fixes, don't have any effect on what you're going to get. Both Hardware and software mode are equally effected. 

I'm using version 0.9.6 of the emulator currently and that runs fine, but later versions sometime after 0.9.6 seem to have these problems. The main builds are v1.3.1-1523-gab962bf and 1.2.1 (stable) that are effected. I don't know when this regression happened for sure. The pictures themselves will show what I'm talking about. There is also skipping during the software mode rendered FMVS in these later builds while 0.9.6 plays them fine. FMVS don't display in hardware mode by the way. Replicating the problem will take about a minute. Just start a new game. It doesn't matter what backend you switch to as well since the problem will persist. 

Gems look good, health bar there, and arrow icon normal.
![good 1](https://cloud.githubusercontent.com/assets/13986398/11601497/75376534-9a88-11e5-9745-5c0a7b71af16.png)

Now they lost their details and are just sold in color. Notice the lack of health bar. Bad arrow icon too.
![bad 1](https://cloud.githubusercontent.com/assets/13986398/11601502/7ad5873c-9a88-11e5-8376-bc327c49694c.png)

Look at the Gems on the left on the pause screen.
![good 2](https://cloud.githubusercontent.com/assets/13986398/11601548/c5db9a50-9a88-11e5-89fb-1cef176fcfd4.png)

Now Compare it to this picture.
![bad 2](https://cloud.githubusercontent.com/assets/13986398/11601580/f8ccc06a-9a88-11e5-92fc-0be9c51b2246.png)

Crosshairs
![good 3](https://cloud.githubusercontent.com/assets/13986398/11601588/0136343e-9a89-11e5-8d31-3d712fc15d33.png)

Now there is no crosshairs in the later builds
![bad 3](https://cloud.githubusercontent.com/assets/13986398/11601609/1af2fd80-9a89-11e5-967b-25c8b45e7713.png)

**Comment by willkuer** [comment]
Please try to increase vu clamping accuracy to full + preserve sign and/or user superVU inszead of microVU.

**Comment by Yui12** [comment]
I just tried what you suggested, but there is no change. Still the same problem.

**Comment by prafullpcsx2** [comment]
The bug report seems incorrect. I tried very hard to reproduce the bug on my system but it works just fine.

**Comment by Yui12** [comment]
Can you tell me your settings because have no idea why I have that problem and not you?

**Comment by ramapcsx2** [comment]
Most likely is a bug in one of the GSdx revisions you use.
Make sure to use 2 seperate PCSX2 install folders in portable install mode.
Keep the old 0.9.6 setup in one, and your newer revisions in the other.

**Comment by Yui12** [comment]
My folders are separated though of course the only thing that isn't new is the lillypad settings that I copied over. All my installations are binary. I hate using installers so I never used the installer version of this emulator. I'm not everything in one folder. 

If this problem can't be solved, then whatever. I only wanted to bring this up since I was noticing a number of regressions piling up in same games, and hopefully it could be one single issue that is causing it which is why I reported it. I'm pretty done with the game already, so it won't matter anymore and using an older version of the emulator to play it is no big deal tome.

**Comment by prafullpcsx2** [comment]
Ok, I managed to recreate the bug on my system. It's very interesting one. 

Disable memory cards - Bug will never occur.
Enable card & Use SW mode only- Bug will never occur.
Enable card, make a save at start & Use HW mode- Bug won't occur until you continue playing.

Now you close PCSX2. Restart PCSX2 and use HW mode (with card enabled) -Bug occurs and even pressing f9 to switch to SW mode doesn't help.

It even happens with 0.9.6 release if you disable all speed hacks but strangely it doesn't happen on 0.9.6 if speed hacks are enabled.

So the bug occurs only in HW mode and that too if there is an existing save of the game on memory card. My guess is first memory card loading screen causes corruption in Gsdx HW mode which results in the bug. That seems correct because if you start the game in SW mode and switch to HW mode after that screen the bug doesn't occur.

Not worth wasting time to fix IMHO.

**Comment by Yui12** [comment]
I thought it was my imagination, but I remember doing this when I forgot to turn it back to HW mode after the first two FMVs before a new game, and the stuff did show up correctly. I thought it was a fluke from updating my drivers since I didn't know that until you mentioned it. I didn't mention this until now since i was thinking that I got my versions mixed up when I was still using 0.9.6., but yeah, this issue is a bizarre one, and very minor. If it doesn't effect other games, then there is no need to bother. I posted it since I was fearing that it did, or does it?

**Comment by willkuer** [comment]
I think there are some games that require booting in a certain fashion. The funny thing here is to wait for the memory card. I think this is unique.

**Comment by lightningterror** [comment]
There are some 1s or less texture corruptions during the loading screens with memory cards inserted.

Block dump (rename to .rar).
[Portal Runner [NTSC-U] [SLUS-20003] (2018-01-22 23-49-48).zip](https://github.com/PCSX2/pcsx2/files/1749853/Portal.Runner.NTSC-U.SLUS-20003.2018-01-22.23-49-48.zip)

**Comment by prafullpcsx2** [comment]
I had a closer look at this and I found that bug was introduced in this commit:-

https://github.com/PCSX2/pcsx2/commit/9aabcc1701ea32315129a1ca26034c759c105979

Also very recently the bug has worsened in this commit:-

https://github.com/PCSX2/pcsx2/commit/b8ed34a277dd00bfc47a864acff096039f885b85

This line of the code effects it:-

(this->*m_fpGIFRegHandlers[((GIFPackedReg*)mem)->A_D.ADDR & 0x7F])(&((GIFPackedReg*)mem)->r);

**Comment by prafullpcsx2** [comment]
Can't reproduce the bug on latest master. Must have been fixed at some point between August and Now.

**Comment by Yui12** [comment]
> 
> 
> Can't reproduce the bug on latest master. Must have been fixed at some point between August and Now.

It's a shame since the current build finally works properly, but pad emulation is busted right now so I can't use it. My controller doesn't even work properly in the current build. After this long-standing issue suddenly gets fixed suddenly something else breaks, so I'll have to wait until the pad problem is fixed.  I tired builds that are a few months older and the graphic problem is still there. The most recent one I had was even worse too.

**Comment by refractionpcsx2** [comment]
What is the pad issue you're experiencing?

**Comment by Yui12** [comment]
My left analog stick isn't working right. I can't move up or down.

**Comment by refractionpcsx2** [comment]
That's odd, have you tried remapping the left analog manually?

**Comment by Yui12** [comment]
Yes. Every button too.

**Comment by refractionpcsx2** [comment]
@GovanifY might need looking in to

**Comment by Yui12** [comment]
Alright. I fixed it. I had to delete everything and start fresh 100% to get rid of the strange problem. I guess it's safe to safe this issue has been fixed, for now.

**Comment by refractionpcsx2** [comment]
oh okay, glad you managed to sort it :)
