### ISSUE TITLE
[BUG]: Soul Calibur III - Black horizontal lines

### ISSUE THREAD

**Issue by skolomir** [PCSX2/pcsx2#12148]
### Describe the Bug

SLUS-21216 - Soul Calibur III

CRC:
027C604C

In the following pictures you can see the black horizontal lines. More precisely, they are transparent, with a certain level of darkening, but they are best seen on a black background.

![Image](https://github.com/user-attachments/assets/368a67da-7c46-406e-a9b1-a5f0edbb0305)
![Image](https://github.com/user-attachments/assets/6d217b18-1e4b-4e7f-85fc-25a9d2d31b03)
![Image](https://github.com/user-attachments/assets/50f35432-470d-487a-aed2-638c093fb9c1)

On images below I used upscaled options, it is 3x upscaling (~1080), black lines are more visible, than on images above.
![Image](https://github.com/user-attachments/assets/6cf1b107-8400-4611-9e88-1a4a34c5ac6b)
![Image](https://github.com/user-attachments/assets/8bad4fef-fa57-4255-b266-af2a5f193071)
![Image](https://github.com/user-attachments/assets/9dc19e2f-dac3-4276-9fe1-854153990826)

### Reproduction Steps

I didn't use any patches (widescreen, or game codes for unlimited heath) with pnach file. This game contains settings in the options for widescreen, without patches.

All what I did, I started this game with default settings.

Only solution for "solving problem" is to use

Dithering: off
Or:
Dithering: Force 32 bit

Dithering off:
![Image](https://github.com/user-attachments/assets/4c71b164-6d43-4a27-9831-2a8353f73bcc)

But, with this solution I can't see real black color, I see grey instead of black.

So, disabling dithering, is not solving problem - it remove black lines, but also remove black color.

Another, but not quite successful solution or workaround is to check the option Screen Offsets and Show Overscan:
![Image](https://github.com/user-attachments/assets/c6b81abb-36f7-4401-bc04-6c4bf7a594cf)

Result:
![Image](https://github.com/user-attachments/assets/f0f192fb-040c-4935-935e-5d0205110fca)

As you see, image misadventages of this method is that image is not full screen.

I tried with differen options, with graphich fixes, without graphic fixes, with automatic fixes, with manula fixes, with all renderer (Vulkan, DirectX, OpenGl. Software), but it didn't solve the problem.

I tried this game on PCSX2 1.6 and I didn't have horizontal black lines, but I think tham black is not black on PCSX2 1.6, it is grey.

### Expected Behavior

I expect to see clear image, without any lines over it.

### PCSX2 Revision

2.3.86

### Operating System

Windows 10 (64bit)

### CPU

i5 10400

### GPU

Nvidia 1650

### GS Settings

Only non default settings which I used is different harware renderer and upscaling options.
I used ingame textures (internal textures), didn't try with external hd textures.

### Emulation Settings

Most often I use Vulcan and 3x for image scaling. I use other renderers if vulcan doesn't work. In the end, I try with software mode, but in this case it didn't give a solution either. Also I use Anisotropic settings 16x, but it doesn't matter is this option on or off.

### Logs & Dumps

I don't have any log files, but I can say that this problem is not something what was solved. I noticed this problem before few months, but I thought that is already reported.

Wiki page
https://wiki.pcsx2.net/Soulcalibur_III

says that this problem (black horizontal stripes) is solved, all what I need is to use latest nighly version, but that is not true.

This prolem is already reported on forum in 2023. under title
Horizontal scanlike overlaying lines. (Multiple games)

Link is
https://forums.pcsx2.net/Thread-Horizontal-scanlike-overlaying-lines-Multiple-games

but this problem is still not solved.

**Comment by lightningterror** [comment]
Can you post a gs dump of the issue?

**Comment by skolomir** [comment]
In Documents folder
...\Documents\PCSX2\gamesettings
I have 
SLUS-21216_027C604C.ini
file, but I cen't upload it, not alowed to upload ini file.

That file contains only this:
[EmuCore/GS]
AspectRatio = 16:9
FMVAspectRatioSwitch = 16:9

Anothref file with settins is
PCSX2.ini
which is in folder
...\Documents\PCSX2\inis

This file contains 546 lines:

[UI]
SettingsVersion = 1
InhibitScreensaver = true
ConfirmShutdown = false
StartPaused = false
PauseOnFocusLoss = false
StartFullscreen = false
DoubleClickTogglesFullscreen = true
HideMouseCursor = true
RenderToSeparateWindow = true
HideMainWindowWhenRunning = false
DisableWindowResize = false
PreferEnglishGameList = false
Theme = darkfusion
SetupWizardIncomplete = false
DisplayWindowGeometry = AdnQywADAAAAAAHAAAAAVgAABDkAAAIVAAABwAAAAHUAAAQ5AAACFQAAAAAAAAAABQAAAAHAAAAAdQAABDkAAAIV
MainWindowGeometry = AdnQywADAAAAAACFAAAADgAABJ4AAALGAAAAhQAAAC0AAASeAAACxgAAAAAAAAAABQAAAACFAAAALQAABJ4AAALG
MainWindowState = AAAA/wAAAAD9AAAAAAAABBoAAAJvAAAABAAAAAQAAAAIAAAACPwAAAABAAAAAgAAAAEAAAAOAHQAbwBvAGwAQgBhAHIAAAAAAP////8AAAAAAAAAAA==
ShowAdvancedSettings = true
GameListGridView = false
GameListShowCoverTitles = true
EnableMouseMapping = false


[Folders]
Bios = ..\..\..\..\EMULATORI\PCSX2 PS2\bios\Playstation 2 BIOS Collection\SCPH-90001_BIOS_V18_USA_230_(NTSC)
Snapshots = snaps
Savestates = sstates
MemoryCards = memcards
Logs = logs
Cheats = cheats
Patches = patches
UserResources = resources
Cache = cache
Textures = textures
InputProfiles = inputprofiles
Videos = videos


[EmuCore]
CdvdVerboseReads = false
CdvdDumpBlocks = false
CdvdPrecache = false
EnablePatches = true
EnableCheats = true
EnablePINE = false
EnableFastBoot = true
EnableFastBootFastForward = false
EnableThreadPinning = false
EnableRecordingTools = true
EnableGameFixes = true
SaveStateOnShutdown = false
EnableDiscordPresence = false
InhibitScreensaver = true
HostFs = false
BackupSavestate = true
SavestateZstdCompression = true
McdFolderAutoManage = true
WarnAboutUnsafeSettings = true
GzipIsoIndexTemplate = $(f).pindex.tmp
PINESlot = 28011
BlockDumpSaveDirectory = 


[EmuCore/Speedhacks]
EECycleRate = 0
EECycleSkip = 0
fastCDVD = false
IntcStat = true
WaitLoop = true
vuFlagHack = true
vuThread = false
vu1Instant = true


[EmuCore/CPU]
FPU.DenormalsAreZero = true
FPU.Roundmode = 3
FPUDiv.DenormalsAreZero = true
FPUDiv.Roundmode = 0
VU0.DenormalsAreZero = true
VU0.Roundmode = 3
VU1.DenormalsAreZero = true
VU1.Roundmode = 3
ExtraMemory = false


[EmuCore/CPU/Recompiler]
EnableEE = true
EnableIOP = true
EnableEECache = false
EnableVU0 = true
EnableVU1 = true
EnableFastmem = true
PauseOnTLBMiss = false
vu0Overflow = true
vu0ExtraOverflow = false
vu0SignOverflow = false
vu0Underflow = false
vu1Overflow = true
vu1ExtraOverflow = false
vu1SignOverflow = false
vu1Underflow = false
fpuOverflow = true
fpuExtraOverflow = false
fpuFullMode = false


[EmuCore/GS]
VsyncEnable = true
DisableMailboxPresentation = false
ExtendedUpscalingMultipliers = false
VsyncQueueSize = 2
FramerateNTSC = 59.94
FrameratePAL = 50
AspectRatio = 16:9
FMVAspectRatioSwitch = 16:9
ScreenshotSize = 0
ScreenshotFormat = 0
ScreenshotQuality = 50
StretchY = 100
CropLeft = 0
CropTop = 0
CropRight = 0
CropBottom = 0
pcrtc_antiblur = true
disable_interlace_offset = false
pcrtc_offsets = false
pcrtc_overscan = false
IntegerScaling = false
UseDebugDevice = false
UseBlitSwapChain = false
DisableShaderCache = false
DisableFramebufferFetch = false
DisableVertexShaderExpand = false
SkipDuplicateFrames = false
OsdShowMessages = true
OsdShowSpeed = true
OsdShowFPS = true
OsdShowCPU = true
OsdShowGPU = true
OsdShowResolution = false
OsdShowGSStats = false
OsdShowIndicators = true
OsdShowSettings = false
OsdShowInputs = false
OsdShowFrameTimes = false
HWSpinGPUForReadbacks = false
HWSpinCPUForReadbacks = false
paltex = false
autoflush_sw = true
preload_frame_with_gs_data = false
mipmap = true
UserHacks = false
UserHacks_align_sprite_X = false
UserHacks_AutoFlushLevel = 0
UserHacks_CPU_FB_Conversion = false
UserHacks_ReadTCOnClose = false
UserHacks_DisableDepthSupport = false
UserHacks_DisablePartialInvalidation = false
UserHacks_Disable_Safe_Features = false
UserHacks_DisableRenderFixes = false
UserHacks_merge_pp_sprite = false
UserHacks_ForceEvenSpritePosition = false
UserHacks_BilinearHack = 0
UserHacks_NativePaletteDraw = false
UserHacks_TextureInsideRt = 0
UserHacks_EstimateTextureRegion = false
fxaa = false
ShadeBoost = false
dump = false
save = false
savef = false
savet = false
savez = false
DumpReplaceableTextures = false
DumpReplaceableMipmaps = false
DumpTexturesWithFMVActive = false
DumpDirectTextures = true
DumpPaletteTextures = true
LoadTextureReplacements = false
LoadTextureReplacementsAsync = true
PrecacheTextureReplacements = false
EnableVideoCapture = true
EnableVideoCaptureParameters = false
VideoCaptureAutoResolution = false
EnableAudioCapture = true
EnableAudioCaptureParameters = false
linear_present_mode = 1
deinterlace_mode = 0
OsdScale = 100
Renderer = 14
upscale_multiplier = 3
hw_mipmap = true
accurate_blending_unit = 1
filter = 2
texture_preloading = 2
GSDumpCompression = 2
HWDownloadMode = 0
CASMode = 0
CASSharpness = 50
dithering_ps2 = 2
MaxAnisotropy = 16
extrathreads = 3
extrathreads_height = 4
TVShader = 7
UserHacks_SkipDraw_Start = 0
UserHacks_SkipDraw_End = 0
UserHacks_HalfPixelOffset = 0
UserHacks_round_sprite_offset = 0
UserHacks_native_scaling = 0
UserHacks_TCOffsetX = 0
UserHacks_TCOffsetY = 0
UserHacks_CPUSpriteRenderBW = 0
UserHacks_CPUSpriteRenderLevel = 0
UserHacks_CPUCLUTRender = 0
UserHacks_GPUTargetCLUTMode = 0
TriFilter = -1
OverrideTextureBarriers = -1
ShadeBoost_Brightness = 50
ShadeBoost_Contrast = 50
ShadeBoost_Saturation = 50
ExclusiveFullscreenControl = 0
png_compression_level = 1
saven = 0
savel = 5000
CaptureContainer = mp4
VideoCaptureCodec = 
VideoCaptureParameters = 
AudioCaptureCodec = 
AudioCaptureParameters = 
VideoCaptureBitrate = 6000
VideoCaptureWidth = 640
VideoCaptureHeight = 480
AudioCaptureBitrate = 160
Adapter = 
HWDumpDirectory = 
SWDumpDirectory = 
SyncToHostRefreshRate = false
UseVSyncForTiming = false


[SPU2/Debug]
Global_Enable = false
Show_Messages = false
Show_Messages_Key_On_Off = false
Show_Messages_Voice_Off = false
Show_Messages_DMA_Transfer = false
Show_Messages_AutoDMA = false
Show_Messages_CacheStats = false
Log_Register_Access = false
Log_DMA_Transfers = false
Log_WAVE_Output = false
Dump_Info = false
Dump_Memory = false
Dump_Regs = false


[SPU2/Output]
OutputVolume = 100
FastForwardVolume = 100
OutputMuted = false
Backend = Cubeb
SyncMode = TimeStretch
DriverName = 
DeviceName = 
ExpansionMode = Disabled
OutputLatencyMinimal = false
BufferMS = 50
OutputLatencyMS = 50
StretchSequenceLengthMS = 30
StretchSeekWindowMS = 20
StretchOverlapMS = 10
StretchUseQuickSeek = false
StretchUseAAFilter = false
ExpandBlockSize = 2048
ExpandCircularWrap = 90
ExpandShift = 0
ExpandDepth = 1
ExpandFocus = 0
ExpandCenterImage = 1
ExpandFrontSeparation = 1
ExpandRearSeparation = 1
ExpandLowCutoff = 40
ExpandHighCutoff = 90


[DEV9/Eth]
EthEnable = false
EthApi = Unset
EthDevice = 
EthLogDHCP = false
EthLogDNS = false
InterceptDHCP = false
PS2IP = 0.0.0.0
Mask = 0.0.0.0
Gateway = 0.0.0.0
DNS1 = 0.0.0.0
DNS2 = 0.0.0.0
AutoMask = true
AutoGateway = true
ModeDNS1 = Auto
ModeDNS2 = Auto


[DEV9/Eth/Hosts]
Count = 0


[DEV9/Hdd]
HddEnable = false
HddFile = DEV9hdd.raw


[EmuCore/Gamefixes]
VuAddSubHack = false
FpuMulHack = false
XgKickHack = false
EETimingHack = false
InstantDMAHack = false
SoftwareRendererFMVHack = false
SkipMPEGHack = false
OPHFlagHack = false
DMABusyHack = false
VIFFIFOHack = false
VIF1StallHack = false
GIFFIFOHack = false
GoemonTlbHack = false
IbitHack = false
VUSyncHack = false
VUOverflowHack = false
BlitInternalFPSHack = false
FullVU0SyncHack = false


[EmuCore/Profiler]
Enabled = false
RecBlocks_EE = true
RecBlocks_IOP = true
RecBlocks_VU0 = true
RecBlocks_VU1 = true


[EmuCore/Debugger]
ShowDebuggerOnStart = false
AlignMemoryWindowStart = true
FontWidth = 8
FontHeight = 12
WindowWidth = 0
WindowHeight = 0
MemoryViewBytesPerRow = 16


[EmuCore/TraceLog]
Enabled = false
EE.bitset = 0
IOP.bitset = 0


[Achievements]
Enabled = false
ChallengeMode = false
EncoreMode = false
SpectatorMode = false
UnofficialTestMode = false
Notifications = true
LeaderboardNotifications = true
SoundEffects = true
Overlays = true
NotificationsDuration = 5
LeaderboardsDuration = 10


[Filenames]
BIOS = SCPH-90001_BIOS_V18_USA_230.ROM0


[Framerate]
NominalScalar = 1
TurboScalar = 0
SlomoScalar = 0.5


[MemoryCards]
Slot1_Enable = true
Slot1_Filename = Mcd001.ps2
Slot2_Enable = true
Slot2_Filename = Mcd002.ps2
Multitap1_Slot2_Enable = false
Multitap1_Slot2_Filename = Mcd-Multitap1-Slot02.ps2
Multitap1_Slot3_Enable = false
Multitap1_Slot3_Filename = Mcd-Multitap1-Slot03.ps2
Multitap1_Slot4_Enable = false
Multitap1_Slot4_Filename = Mcd-Multitap1-Slot04.ps2
Multitap2_Slot2_Enable = false
Multitap2_Slot2_Filename = Mcd-Multitap2-Slot02.ps2
Multitap2_Slot3_Enable = false
Multitap2_Slot3_Filename = Mcd-Multitap2-Slot03.ps2
Multitap2_Slot4_Enable = false
Multitap2_Slot4_Filename = Mcd-Multitap2-Slot04.ps2


[Logging]
EnableSystemConsole = false
EnableFileLogging = false
EnableTimestamps = true
EnableVerbose = false
EnableEEConsole = false
EnableIOPConsole = false
EnableInputRecordingLogs = true
EnableControllerLogs = false


[GameList]
RecursivePaths = C:\EMULATORI\PCSX2 PS2\ROMS


[InputSources]
Keyboard = true
Mouse = true
SDL = true
DInput = false
XInput = false
SDLControllerEnhancedMode = false
SDLPS5PlayerLED = false


[Hotkeys]
ZoomIn = Keyboard/Control & Keyboard/Plus
ZoomOut = Keyboard/Control & Keyboard/Minus
OpenPauseMenu = Keyboard/Escape
TogglePause = Keyboard/Space
ToggleFullscreen = Keyboard/Alt & Keyboard/Return
ToggleFrameLimit = Keyboard/F4
ToggleTurbo = Keyboard/Tab
ToggleSlowMotion = Keyboard/Shift & Keyboard/Backtab
HoldTurbo = Keyboard/N
InputRecToggleMode = Keyboard/Shift & Keyboard/R
PreviousSaveStateSlot = Keyboard/F3
NextSaveStateSlot = Keyboard/F2
SaveStateToSlot = Keyboard/Shift & Keyboard/F1
LoadStateFromSlot = Keyboard/F1
Screenshot = Keyboard/F8
GSDumpSingleFrame = Keyboard/Shift & Keyboard/F8
GSDumpMultiFrame = Keyboard/Control & Keyboard/Shift & Keyboard/F8
ToggleSoftwareRendering = Keyboard/F10
CycleAspectRatio = Keyboard/F9
ToggleMipmapMode = Keyboard/Insert
CycleInterlaceMode = Keyboard/F5


[Pad]
MultitapPort1 = false
MultitapPort2 = false
PointerXScale = 8
PointerYScale = 8


[Pad1]
Type = DualShock2
InvertL = 0
InvertR = 0
Deadzone = 0
AxisScale = 1.33
ButtonDeadzone = 0
PressureModifier = 0.5
Up = Keyboard/Up
Right = Keyboard/Right
Down = Keyboard/Down
Left = Keyboard/Left
Triangle = Keyboard/Z
Circle = Keyboard/S
Cross = Keyboard/A
Square = Keyboard/X
Select = Keyboard/5
Start = Keyboard/1
L1 = Keyboard/Q
L2 = Keyboard/E
R1 = Keyboard/W
R2 = Keyboard/R
L3 = Keyboard/T
R3 = Keyboard/Y
LUp = Keyboard/I
LRight = Keyboard/L
LDown = Keyboard/K
LLeft = Keyboard/J
RUp = Keyboard/Numpad5
RRight = Keyboard/Numpad3
RDown = Keyboard/Numpad2
RLeft = Keyboard/Numpad1
LargeMotorScale = 1
SmallMotorScale = 1


[Pad2]
Type = None
Triangle = Keyboard/Period
Circle = Keyboard/Apostrophe
Cross = Keyboard/Semicolon
Square = Keyboard/Slash
Select = Keyboard/6
Start = Keyboard/2
L1 = Keyboard/O
L2 = Keyboard/BracketLeft
R1 = Keyboard/P
R2 = Keyboard/BracketRight
L3 = Keyboard/M
R3 = Keyboard/Comma


[Pad3]
Type = None


[Pad4]
Type = None


[Pad5]
Type = None


[Pad6]
Type = None


[Pad7]
Type = None


[Pad8]
Type = None


[USB1]
Type = None


[USB2]
Type = None


[GameListTableView]
SortColumn = Title
SortDescending = false

Maybe you thought on same another file.

**Comment by skolomir** [comment]
In Documents folder
...\Documents\PCSX2\gamesettings
I have 
SLUS-21216_027C604C.ini
file, but I cen't upload it, not alowed to upload ini file.

That file contains only this:
[EmuCore/GS]
AspectRatio = 16:9
FMVAspectRatioSwitch = 16:9

Anothref file with settins is
PCSX2.ini
which is in folder
...\Documents\PCSX2\inis

This file contains 546 lines:

[UI]
SettingsVersion = 1
InhibitScreensaver = true
ConfirmShutdown = false
StartPaused = false
PauseOnFocusLoss = false
StartFullscreen = false
DoubleClickTogglesFullscreen = true
HideMouseCursor = true
RenderToSeparateWindow = true
HideMainWindowWhenRunning = false
DisableWindowResize = false
PreferEnglishGameList = false
Theme = darkfusion
SetupWizardIncomplete = false
DisplayWindowGeometry = AdnQywADAAAAAAHAAAAAVgAABDkAAAIVAAABwAAAAHUAAAQ5AAACFQAAAAAAAAAABQAAAAHAAAAAdQAABDkAAAIV
MainWindowGeometry = AdnQywADAAAAAACFAAAADgAABJ4AAALGAAAAhQAAAC0AAASeAAACxgAAAAAAAAAABQAAAACFAAAALQAABJ4AAALG
MainWindowState = AAAA/wAAAAD9AAAAAAAABBoAAAJvAAAABAAAAAQAAAAIAAAACPwAAAABAAAAAgAAAAEAAAAOAHQAbwBvAGwAQgBhAHIAAAAAAP////8AAAAAAAAAAA==
ShowAdvancedSettings = true
GameListGridView = false
GameListShowCoverTitles = true
EnableMouseMapping = false


[Folders]
Bios = ..\..\..\..\EMULATORI\PCSX2 PS2\bios\Playstation 2 BIOS Collection\SCPH-90001_BIOS_V18_USA_230_(NTSC)
Snapshots = snaps
Savestates = sstates
MemoryCards = memcards
Logs = logs
Cheats = cheats
Patches = patches
UserResources = resources
Cache = cache
Textures = textures
InputProfiles = inputprofiles
Videos = videos


[EmuCore]
CdvdVerboseReads = false
CdvdDumpBlocks = false
CdvdPrecache = false
EnablePatches = true
EnableCheats = true
EnablePINE = false
EnableFastBoot = true
EnableFastBootFastForward = false
EnableThreadPinning = false
EnableRecordingTools = true
EnableGameFixes = true
SaveStateOnShutdown = false
EnableDiscordPresence = false
InhibitScreensaver = true
HostFs = false
BackupSavestate = true
SavestateZstdCompression = true
McdFolderAutoManage = true
WarnAboutUnsafeSettings = true
GzipIsoIndexTemplate = $(f).pindex.tmp
PINESlot = 28011
BlockDumpSaveDirectory = 


[EmuCore/Speedhacks]
EECycleRate = 0
EECycleSkip = 0
fastCDVD = false
IntcStat = true
WaitLoop = true
vuFlagHack = true
vuThread = false
vu1Instant = true


[EmuCore/CPU]
FPU.DenormalsAreZero = true
FPU.Roundmode = 3
FPUDiv.DenormalsAreZero = true
FPUDiv.Roundmode = 0
VU0.DenormalsAreZero = true
VU0.Roundmode = 3
VU1.DenormalsAreZero = true
VU1.Roundmode = 3
ExtraMemory = false


[EmuCore/CPU/Recompiler]
EnableEE = true
EnableIOP = true
EnableEECache = false
EnableVU0 = true
EnableVU1 = true
EnableFastmem = true
PauseOnTLBMiss = false
vu0Overflow = true
vu0ExtraOverflow = false
vu0SignOverflow = false
vu0Underflow = false
vu1Overflow = true
vu1ExtraOverflow = false
vu1SignOverflow = false
vu1Underflow = false
fpuOverflow = true
fpuExtraOverflow = false
fpuFullMode = false


[EmuCore/GS]
VsyncEnable = true
DisableMailboxPresentation = false
ExtendedUpscalingMultipliers = false
VsyncQueueSize = 2
FramerateNTSC = 59.94
FrameratePAL = 50
AspectRatio = 16:9
FMVAspectRatioSwitch = 16:9
ScreenshotSize = 0
ScreenshotFormat = 0
ScreenshotQuality = 50
StretchY = 100
CropLeft = 0
CropTop = 0
CropRight = 0
CropBottom = 0
pcrtc_antiblur = true
disable_interlace_offset = false
pcrtc_offsets = false
pcrtc_overscan = false
IntegerScaling = false
UseDebugDevice = false
UseBlitSwapChain = false
DisableShaderCache = false
DisableFramebufferFetch = false
DisableVertexShaderExpand = false
SkipDuplicateFrames = false
OsdShowMessages = true
OsdShowSpeed = true
OsdShowFPS = true
OsdShowCPU = true
OsdShowGPU = true
OsdShowResolution = false
OsdShowGSStats = false
OsdShowIndicators = true
OsdShowSettings = false
OsdShowInputs = false
OsdShowFrameTimes = false
HWSpinGPUForReadbacks = false
HWSpinCPUForReadbacks = false
paltex = false
autoflush_sw = true
preload_frame_with_gs_data = false
mipmap = true
UserHacks = false
UserHacks_align_sprite_X = false
UserHacks_AutoFlushLevel = 0
UserHacks_CPU_FB_Conversion = false
UserHacks_ReadTCOnClose = false
UserHacks_DisableDepthSupport = false
UserHacks_DisablePartialInvalidation = false
UserHacks_Disable_Safe_Features = false
UserHacks_DisableRenderFixes = false
UserHacks_merge_pp_sprite = false
UserHacks_ForceEvenSpritePosition = false
UserHacks_BilinearHack = 0
UserHacks_NativePaletteDraw = false
UserHacks_TextureInsideRt = 0
UserHacks_EstimateTextureRegion = false
fxaa = false
ShadeBoost = false
dump = false
save = false
savef = false
savet = false
savez = false
DumpReplaceableTextures = false
DumpReplaceableMipmaps = false
DumpTexturesWithFMVActive = false
DumpDirectTextures = true
DumpPaletteTextures = true
LoadTextureReplacements = false
LoadTextureReplacementsAsync = true
PrecacheTextureReplacements = false
EnableVideoCapture = true
EnableVideoCaptureParameters = false
VideoCaptureAutoResolution = false
EnableAudioCapture = true
EnableAudioCaptureParameters = false
linear_present_mode = 1
deinterlace_mode = 0
OsdScale = 100
Renderer = 14
upscale_multiplier = 3
hw_mipmap = true
accurate_blending_unit = 1
filter = 2
texture_preloading = 2
GSDumpCompression = 2
HWDownloadMode = 0
CASMode = 0
CASSharpness = 50
dithering_ps2 = 2
MaxAnisotropy = 16
extrathreads = 3
extrathreads_height = 4
TVShader = 7
UserHacks_SkipDraw_Start = 0
UserHacks_SkipDraw_End = 0
UserHacks_HalfPixelOffset = 0
UserHacks_round_sprite_offset = 0
UserHacks_native_scaling = 0
UserHacks_TCOffsetX = 0
UserHacks_TCOffsetY = 0
UserHacks_CPUSpriteRenderBW = 0
UserHacks_CPUSpriteRenderLevel = 0
UserHacks_CPUCLUTRender = 0
UserHacks_GPUTargetCLUTMode = 0
TriFilter = -1
OverrideTextureBarriers = -1
ShadeBoost_Brightness = 50
ShadeBoost_Contrast = 50
ShadeBoost_Saturation = 50
ExclusiveFullscreenControl = 0
png_compression_level = 1
saven = 0
savel = 5000
CaptureContainer = mp4
VideoCaptureCodec = 
VideoCaptureParameters = 
AudioCaptureCodec = 
AudioCaptureParameters = 
VideoCaptureBitrate = 6000
VideoCaptureWidth = 640
VideoCaptureHeight = 480
AudioCaptureBitrate = 160
Adapter = 
HWDumpDirectory = 
SWDumpDirectory = 
SyncToHostRefreshRate = false
UseVSyncForTiming = false


[SPU2/Debug]
Global_Enable = false
Show_Messages = false
Show_Messages_Key_On_Off = false
Show_Messages_Voice_Off = false
Show_Messages_DMA_Transfer = false
Show_Messages_AutoDMA = false
Show_Messages_CacheStats = false
Log_Register_Access = false
Log_DMA_Transfers = false
Log_WAVE_Output = false
Dump_Info = false
Dump_Memory = false
Dump_Regs = false


[SPU2/Output]
OutputVolume = 100
FastForwardVolume = 100
OutputMuted = false
Backend = Cubeb
SyncMode = TimeStretch
DriverName = 
DeviceName = 
ExpansionMode = Disabled
OutputLatencyMinimal = false
BufferMS = 50
OutputLatencyMS = 50
StretchSequenceLengthMS = 30
StretchSeekWindowMS = 20
StretchOverlapMS = 10
StretchUseQuickSeek = false
StretchUseAAFilter = false
ExpandBlockSize = 2048
ExpandCircularWrap = 90
ExpandShift = 0
ExpandDepth = 1
ExpandFocus = 0
ExpandCenterImage = 1
ExpandFrontSeparation = 1
ExpandRearSeparation = 1
ExpandLowCutoff = 40
ExpandHighCutoff = 90


[DEV9/Eth]
EthEnable = false
EthApi = Unset
EthDevice = 
EthLogDHCP = false
EthLogDNS = false
InterceptDHCP = false
PS2IP = 0.0.0.0
Mask = 0.0.0.0
Gateway = 0.0.0.0
DNS1 = 0.0.0.0
DNS2 = 0.0.0.0
AutoMask = true
AutoGateway = true
ModeDNS1 = Auto
ModeDNS2 = Auto


[DEV9/Eth/Hosts]
Count = 0


[DEV9/Hdd]
HddEnable = false
HddFile = DEV9hdd.raw


[EmuCore/Gamefixes]
VuAddSubHack = false
FpuMulHack = false
XgKickHack = false
EETimingHack = false
InstantDMAHack = false
SoftwareRendererFMVHack = false
SkipMPEGHack = false
OPHFlagHack = false
DMABusyHack = false
VIFFIFOHack = false
VIF1StallHack = false
GIFFIFOHack = false
GoemonTlbHack = false
IbitHack = false
VUSyncHack = false
VUOverflowHack = false
BlitInternalFPSHack = false
FullVU0SyncHack = false


[EmuCore/Profiler]
Enabled = false
RecBlocks_EE = true
RecBlocks_IOP = true
RecBlocks_VU0 = true
RecBlocks_VU1 = true


[EmuCore/Debugger]
ShowDebuggerOnStart = false
AlignMemoryWindowStart = true
FontWidth = 8
FontHeight = 12
WindowWidth = 0
WindowHeight = 0
MemoryViewBytesPerRow = 16


[EmuCore/TraceLog]
Enabled = false
EE.bitset = 0
IOP.bitset = 0


[Achievements]
Enabled = false
ChallengeMode = false
EncoreMode = false
SpectatorMode = false
UnofficialTestMode = false
Notifications = true
LeaderboardNotifications = true
SoundEffects = true
Overlays = true
NotificationsDuration = 5
LeaderboardsDuration = 10


[Filenames]
BIOS = SCPH-90001_BIOS_V18_USA_230.ROM0


[Framerate]
NominalScalar = 1
TurboScalar = 0
SlomoScalar = 0.5


[MemoryCards]
Slot1_Enable = true
Slot1_Filename = Mcd001.ps2
Slot2_Enable = true
Slot2_Filename = Mcd002.ps2
Multitap1_Slot2_Enable = false
Multitap1_Slot2_Filename = Mcd-Multitap1-Slot02.ps2
Multitap1_Slot3_Enable = false
Multitap1_Slot3_Filename = Mcd-Multitap1-Slot03.ps2
Multitap1_Slot4_Enable = false
Multitap1_Slot4_Filename = Mcd-Multitap1-Slot04.ps2
Multitap2_Slot2_Enable = false
Multitap2_Slot2_Filename = Mcd-Multitap2-Slot02.ps2
Multitap2_Slot3_Enable = false
Multitap2_Slot3_Filename = Mcd-Multitap2-Slot03.ps2
Multitap2_Slot4_Enable = false
Multitap2_Slot4_Filename = Mcd-Multitap2-Slot04.ps2


[Logging]
EnableSystemConsole = false
EnableFileLogging = false
EnableTimestamps = true
EnableVerbose = false
EnableEEConsole = false
EnableIOPConsole = false
EnableInputRecordingLogs = true
EnableControllerLogs = false


[GameList]
RecursivePaths = C:\EMULATORI\PCSX2 PS2\ROMS


[InputSources]
Keyboard = true
Mouse = true
SDL = true
DInput = false
XInput = false
SDLControllerEnhancedMode = false
SDLPS5PlayerLED = false


[Hotkeys]
ZoomIn = Keyboard/Control & Keyboard/Plus
ZoomOut = Keyboard/Control & Keyboard/Minus
OpenPauseMenu = Keyboard/Escape
TogglePause = Keyboard/Space
ToggleFullscreen = Keyboard/Alt & Keyboard/Return
ToggleFrameLimit = Keyboard/F4
ToggleTurbo = Keyboard/Tab
ToggleSlowMotion = Keyboard/Shift & Keyboard/Backtab
HoldTurbo = Keyboard/N
InputRecToggleMode = Keyboard/Shift & Keyboard/R
PreviousSaveStateSlot = Keyboard/F3
NextSaveStateSlot = Keyboard/F2
SaveStateToSlot = Keyboard/Shift & Keyboard/F1
LoadStateFromSlot = Keyboard/F1
Screenshot = Keyboard/F8
GSDumpSingleFrame = Keyboard/Shift & Keyboard/F8
GSDumpMultiFrame = Keyboard/Control & Keyboard/Shift & Keyboard/F8
ToggleSoftwareRendering = Keyboard/F10
CycleAspectRatio = Keyboard/F9
ToggleMipmapMode = Keyboard/Insert
CycleInterlaceMode = Keyboard/F5


[Pad]
MultitapPort1 = false
MultitapPort2 = false
PointerXScale = 8
PointerYScale = 8


[Pad1]
Type = DualShock2
InvertL = 0
InvertR = 0
Deadzone = 0
AxisScale = 1.33
ButtonDeadzone = 0
PressureModifier = 0.5
Up = Keyboard/Up
Right = Keyboard/Right
Down = Keyboard/Down
Left = Keyboard/Left
Triangle = Keyboard/Z
Circle = Keyboard/S
Cross = Keyboard/A
Square = Keyboard/X
Select = Keyboard/5
Start = Keyboard/1
L1 = Keyboard/Q
L2 = Keyboard/E
R1 = Keyboard/W
R2 = Keyboard/R
L3 = Keyboard/T
R3 = Keyboard/Y
LUp = Keyboard/I
LRight = Keyboard/L
LDown = Keyboard/K
LLeft = Keyboard/J
RUp = Keyboard/Numpad5
RRight = Keyboard/Numpad3
RDown = Keyboard/Numpad2
RLeft = Keyboard/Numpad1
LargeMotorScale = 1
SmallMotorScale = 1


[Pad2]
Type = None
Triangle = Keyboard/Period
Circle = Keyboard/Apostrophe
Cross = Keyboard/Semicolon
Square = Keyboard/Slash
Select = Keyboard/6
Start = Keyboard/2
L1 = Keyboard/O
L2 = Keyboard/BracketLeft
R1 = Keyboard/P
R2 = Keyboard/BracketRight
L3 = Keyboard/M
R3 = Keyboard/Comma


[Pad3]
Type = None


[Pad4]
Type = None


[Pad5]
Type = None


[Pad6]
Type = None


[Pad7]
Type = None


[Pad8]
Type = None


[USB1]
Type = None


[USB2]
Type = None


[GameListTableView]
SortColumn = Title
SortDescending = false

Maybe you thought on same another file.

**Comment by F0bes** [comment]
```
How To Create A GS Dump
What is a GS dump?
A GS dump is a dump of PS2 graphics data. The dump allows helpers, testers and developers to figure out how to fix graphics bugs.

Where do I make the dump?
Get to a point in your game where the graphics bug is clearly visible. The issue must appear on your screen in order for it to be captured in the dump.

How do I make the dump?
Use the key combination Shift + F8 or use Tools > Save Single Frame GS Dump

Where does the GS dump save to?
Tools > Open Data Directory, then look for the snaps folder.

Your graphics settings DO NOT affect the dump, and you will not need to change renderers, hardware fixes or any other settings.
```

**Comment by skolomir** [comment]
Dump is in some kind of archive. I can't upload it like archive or gs extendsion, because this site doesn't allow it.

Name of archive:
Soul Calibur III_SLUS-21216_20250102205816.gs.zst

Name of extracted file:
Soul Calibur III_SLUS-21216_20250102205816.gs

So, to be able to upload it, I changed gs extension to dmp.

Name of uploaded file is:
Soul Calibur III_SLUS-21216_20250102205816.dmp

[Soul Calibur III_SLUS-21216_20250102205816.dmp](https://github.com/user-attachments/files/18294080/Soul.Calibur.III_SLUS-21216_20250102205816.dmp)

If you need gs extension, just rename dmp to gs.

**Comment by Mrlinkwii** [comment]
hardware seems to match SW at native res as of 2.3.245

**Comment by skolomir** [comment]
I tried now 2.3.246 version, Vulkan renderer, and problem still exist.

**Comment by Moonalesca** [comment]
I've just fixed this issue myself. Go to Properties > Graphics > Rendering and set Dithering to "Force 32 bit".

**Comment by skolomir** [comment]
Changing dithering options to force on 32 bit is not solution, it makes black color to become grey. I suppose that background on black image should be black. But, if you instead of 32 bit chose Off, than you will have black image. But, with Off, I have warning about blending options.

Dithering: Off
Description: Black image (I suppose this is correct)
Warning:
Dithering is disabled. This will cause color banding in same games.

Dithering: Sscaled (default)
Description: Horizontal stripe lines (this is problem)
No warning.

Dithering: Unscaled (default)
Description: Horizontal stripe lines (this is problem)
No warning.

Dithering: 32 bit
Description: Grey image instead of black (I suppose it should be black)
Warning:
Dithering is sidabled. This will cause color banding is some games.

I reported problem here:
https://wiki.pcsx2.net/SoulCalibur_III

**Comment by Mrlinkwii** [comment]
hardware renderer with default settings at native res seems to match SW  as of v2.7.106

**Comment by refractionpcsx2** [comment]
Can't notice it myself, however if it's only happening when dithering is enabled, this isn't a bug with the emulator, it's the scaling of the dithering effect on your monitor causing a phasing like effect, you can try changing the window size or the upscale amount, or using "Force 32bit" as you have been, but it's not really a fixable issue.

You could also maybe try the downscale filters, I have no idea if they help.

Edit: Okay I couldn't see it because I have the RGSS filter enabled, so I suggest you do that, if it's an issue for you.

<img width="703" height="153" alt="Image" src="https://github.com/user-attachments/assets/5327fd45-e2b5-4380-835e-7279981267a1" />

**Comment by skolomir** [comment]
In version 2.7.106 the issue still persists. I can no longer see the lines in the middle of the screen, but they are still visible at the top (the upper third of the screen) and at the bottom (the lower third).

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/d8256458-e92e-41af-abdd-2bed9c7a19b0" />


As for the 4xRGSS shader, I’m not using post-processing effects because of the additional performance cost. If the game runs properly, it should run properly without any shaders.

I tested the shader — it removes the lines, but it introduces another issue. When I enable it, black is no longer truly black; it becomes slightly brighter. The screen may appear completely black at first, but as scenes change and images are displayed over a black background, the black level fluctuates — sometimes darker, sometimes lighter.

Example with the shader enabled:
At the start of the fade-in effect, the background is completely black — nothing is visible, not even the logo.
Once the fade-in finishes and the logo is fully visible, the black background becomes noticeably lighter.
After a full fade-out, when the logo disappears from the screen, the background becomes completely black again.

There’s really nothing for me to tweak in the settings at this point. I can only wait for PCSX2 to provide a proper fix and for someone to confirm it, if they notice it before I do.

**Comment by refractionpcsx2** [comment]
The black isn't truely black anyway, it's dithered, the dither is making it brighter, hence the lines on the black screen.  the downsample shader just averages the surrounding pixels which smooths it out.  It was never completely black to begin with.

**Comment by skolomir** [comment]
Image 1 – Comparison of RGB values when the lines are present.
On the left side of the image (the middle part of the screen where no lines are visible), the RGB value is 020202. This is the emulator’s default setting, game resolution set to 3x, 1920×1080. The same settings are used for all images.

On the right side of the image, 4xRGSS is enabled. The RGB value is the same as on the left side of the image, 020202. This indicates a possibility that, if the lines are completely eliminated under default settings, the RGB value may still not reach zero.

Although the RGB values on the left and right sides of the image are identical, it should be noted that the small rectangles forming the left image appear more regular, with a more symmetrical or denser repetition. The right side appears to have lower density, but this may be due to the 4xRGSS post-processing shader being enabled.

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/124ba3de-8066-4391-9dec-902ae11f9276" />

Image 2 – Same as Image 1, but zoomed in
The image is zoomed in to better visualize the difference in rectangle density.

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/c54f617b-fedb-40bc-a612-284f6138d1e3" />

Image 3 – Difference between pure black and the black visible when the 4xRGSS shader is enabled.
The goal is to achieve true black when the logo is displayed, rather than having RGB black transition abruptly into a lighter black. In other words, before the animation begins, the background black should have an RGB value of 000000, and then suddenly shift to 020202. This occurs both when the shader is enabled and when using default settings.

I am not sure whether it is possible to obtain pure black (RGB 0) even when a logo is displayed over it.

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/0dc968ca-ade8-4d2e-8a0d-88cf6344b020" />

Since the Align Sprites option no longer exists, we are now waiting for the integration of another solution. Even if the lines disappear under default settings, the issue of true black RGB (0) versus in-game black RGB (02) will remain.

The only thing that could soften the slightly irritating abrupt jump would be better integration with the fade effect.

So there are two separate problems: the lines and the non-pure black color.

I believe the black screen at the beginning of the game uses a fade effect, but I do not know whether it starts from black with a value of 0 or with a value of 2.

What I can observe with the RGSS shader is that jumps still occur — the abrupt transition is noticeable.

**Comment by refractionpcsx2** [comment]
Align Sprite does still exist

the version with lines is how it should be, just with a phasing effect due to your resolution/window size, and the brights of the lines are probably similar/brighter than with RGSS

the reason it's 020202 and not 000000 is because it's dithering, but the effect isn't being truncated, which is common on the HW renderer because everything is rendered in 32bit and truncation is only done in some cricumstances, I don't know if it's really feasible to do so in this scenario as I'm not aware of what the game is doing to present these black screens.  I would also argue that's such a minor difference, it's really not worth making a fuss over, if you want 100% accuracy, you could try max blending or using software.
