### ISSUE TITLE
Meta: GSdx SW issue

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1562]
Single issue report to centralize all current issue/limitation with the SW renderer.  The trick is to avoid core bug.

**Comment by FlatOutPS2** [comment]
Might be core issue, but potentially GSdx issue:
http://forums.pcsx2.net/Thread-Smackdown-4-Shut-Your-Mouth-special-meter-doesn-t-display-properly

Alpine Racer 3. GSdx issue that also affects SW, there's a CRC hack for HW mode. Without the CRC hack DX11 HW is fine, but DX9 HW, OGL HW and SW modes are affected.

**Comment by TheLastRar** [comment]
Network Profile Wizard (the one built-in with some games), Most text/boxes stuck in top left.
I believe this is a GS emulation issue rather than a core issue. 
https://github.com/PCSX2/pcsx2/issues/287

**Comment by FlatOutPS2** [comment]
Colin McRae Rally 2005 SW issue has been resolved thanks to https://github.com/PCSX2/pcsx2/commit/3994141d4085c6365876efc0c561893cda9aba96

**Comment by gregory38** [comment]
We need to add the jak issue and the explanation in this report.

**Comment by prafullpcsx2** [comment]
Although it wasn't mentioned in this thread but I would like to report that software mode ghosting in Catwoman is also fixed by auto flush hack. HW mode ghosting is same as before.

**Comment by gregory38** [comment]
Good, I wanted to ask you :+1:

**Comment by monsterjamp** [comment]
@gregory38 The cutscenes in Thrillville are cut off even in SW mode. Can you confirm if this is a core bug? There's a GS dump in this forum thread: http://forums.pcsx2.net/Thread-Bug-Report-Thrillville-NTSC-U

**Comment by gregory38** [comment]
@monsterjamp did you test zerogs? Honestly a partial texture upload is likely a core bug.

**Comment by monsterjamp** [comment]
ZeroGS keeps crashing when it gets to the cutscenes so I can't test it.

There's also another issue but this one is only present is SW mode. In the pause menu, the bottom right of the screen is missing.

Hardware mode:
![2016-10-06 13_11_43-slot_ 0 _ speed_ 101 60 36 _ limiter_ normal _ gsdx d3d11 hw _ 640x445 _ bob](https://cloud.githubusercontent.com/assets/7116269/19165020/d3e7f540-8bc7-11e6-95a5-1e1d4458c342.png)


Software mode:
![2016-10-06 13_12_11-slot_ 0 _ speed_ 84 50 26 _ limiter_ normal _ gsdx d3d11 sw _ 640x445 _ bob](https://cloud.githubusercontent.com/assets/7116269/19165027/d7c243b4-8bc7-11e6-8805-213039b4eef6.png)

GS dump: http://www.mediafire.com/file/r9b2xgcypbua50q/gsdx_20161006131227.gs

**Comment by FlatOutPS2** [comment]
There's text missing in Pride FC menu's in HW and SW modes. Could be a GSdx issue, here's a GSdump:

[Pride FC missing text.zip](https://github.com/PCSX2/pcsx2/files/514870/Pride.FC.missing.text.zip)

**Comment by FlatOutPS2** [comment]
Burnout 3 still has missing flags in OGL hardware and software modes. The flags can only be seen with the Direct3D HW renderers(see the 3 grey flags in the added screenshot). The flags are not supposed to be grey, but colored American flags.

[Burnout 3 missing flags SW and HW.zip](https://github.com/PCSX2/pcsx2/files/517745/Burnout.3.missing.flags.SW.and.HW.zip)

**Comment by gregory38** [comment]
I just found that GS local memory can wrap around. It explains a bug on Silent Hill 3 FMV. I think it can potentially explain issue on Thrillville. Potentially the end of the FMV is the start of the memory. My guess is that HW will happily overflow the frame buffer whereas SW will hit a wall.

**Comment by gregory38** [comment]
If you use Linux, you can use the new hidden option `wrap_gs_mem = 1` in gsdx.ini. I advice to use it only for the SW renderer.

**Comment by gregory38** [comment]
I gave a look at Thrillville the issue is very close but my option doesn't fix it. The game does some rendering at 0x3C00 which means only 32 pages remain. The rendering is 320x224 so 5*7 pages. It overflows 3 pages (which are the bottom black area)

**Comment by gregory38** [comment]
@monsterjamp I pushed some fixes for Thrillville, the only requirement is a linux OS.

**Comment by gregory38** [comment]
@monsterjamp I pushed some improvements that should work on Windows too (without the option)

**Comment by FlatOutPS2** [comment]
So the option is useless now?

**Comment by gregory38** [comment]
I keep it for debug purpose but it ought to work without it. The wrapping is limited to a couple of key functions.

**Comment by FlatOutPS2** [comment]
Yes, the latest master works with SH3 FMV in Software mode with default settings. Now we only need to confirm it works with Thrillville as well.

**Comment by gregory38** [comment]
#1628 still not clear of the current status

**Comment by DPersonalized** [comment]
In Burnout Revenge, the black gradient behind the objectives text ("Check traffic to beat the Score Targets!", etc.) is completely messed up with all renderers.

![gsdx_20161110222726](https://cloud.githubusercontent.com/assets/8225831/20196935/e969b9ec-a794-11e6-9e3e-5b1985213603.png)

My PS2's currently set up in the living room, and I can only record it using my PC in my room, so I just decided to take a screenshot from the Xbox version (which looks more or less the same, anyway.)

![revenge_xbox_shot](https://cloud.githubusercontent.com/assets/8225831/20196777/2e541e5e-a794-11e6-908f-0890ba17badb.png)

**Comment by FlatOutPS2** [comment]
In `ATV Quad Power Racing 2` quads are missing or appear as a bugged texture in Software mode. It's fine in Hardware mode.

GSDump(rename .pdf to .zip)
[ATV Quad Power Racing 2 - missing AI quads in SW.pdf](https://github.com/PCSX2/pcsx2/files/586675/ATV.Quad.Power.Racing.2.-.missing.AI.quads.in.SW.pdf)

**Comment by MrCK1** [comment]
I finally got Nascar 09 working - it needed EE Cache to boot. There's something going on with the screen height and it doesn't run in SW mode at all. Would a GSDump in HW renderer be useful?

(The screenshot is too "long" to paste here so [here it is](http://forums.pcsx2.net/attachment.php?aid=61512) :P)

**Comment by prafullpcsx2** [comment]
@MrCK1 : Can you please check whether it works with eecache before https://github.com/PCSX2/pcsx2/commit/49b80a4916580838375faf4698a336e898648c6b

**Comment by MrCK1** [comment]
@prafullpcsx2 I just checked and it doesn't work before that point

**Comment by FlatOutPS2** [comment]
And another software mode issue:
http://forums.pcsx2.net/Thread-GSDX-Software-mode-Bug-Report-Arc-The-Lad-End-Of-Darkness-Graphical-glitch

**Comment by FlatOutPS2** [comment]
Alpine Racer 3 issue has been resolved. Quick test indicates it was fixed by the Berserk 8/4 bits commits.

I believe there's still a CRC hack for this game, which can now also be removed.

**Comment by MrCK1** [comment]
Quick question - is it normal for FMVs in SW mode to "bleed" at the bottom of the screen? I've noticed a few games have this.

![gsdx_20170103173031](https://cloud.githubusercontent.com/assets/16314399/21625616/779c0944-d1da-11e6-9c0a-9fa70f56b45c.png)

**Comment by FlatOutPS2** [comment]
No. Is the bottom of the screen black in Hardware mode or does Hardware mode use the full screen?

**Comment by MrCK1** [comment]
No. In the two cases I tested, hardware mode was fine and filled the entire screen like so:

HW:
![gsdx_20170103183414](https://cloud.githubusercontent.com/assets/16314399/21627056/44043562-d1e3-11e6-86cb-ab0ca97a73fa.png)

SW:
![gsdx_20170103183416](https://cloud.githubusercontent.com/assets/16314399/21627064/4f946974-d1e3-11e6-9290-a4a06ba57897.png)

**Comment by FlatOutPS2** [comment]
> EDIT: Found the regression. It was introduced in #1683.

That makes sense. @ssakash already made a PR to fix these issues: https://github.com/PCSX2/pcsx2/pull/1693
It fixes the dump, but be sure to try the PR with the other games you've noticed have the issue just in case.

**Comment by MrCK1** [comment]
Looks good to me so far. 👍

**Comment by gregory38** [comment]
Looking at the into of SotC, it seems to have bad texture when mipmap is enabled (mountain). Could someone confirm it, and tell me if it is a regression/known problem/..

**Comment by FlatOutPS2** [comment]
Smash Court Tennis Pro Tournament has a Software mode issue(it's fine with HW renderers)
http://forums.pcsx2.net/Thread-Bug-Report-Smash-Court-Tennis-Pro-Tournament-USA
And this is also likely a GSdx issue(it's worse in OpenGL HW than any other renderers, but also affects SW):
https://github.com/PCSX2/pcsx2/issues/983

**Comment by gregory38** [comment]
We need some volunteers to test #1843 :+1: So far it fixes Jak3 and Xenosaga issue. But it could explain some others bugs.

And I need a confirmation that #84 still contains some SW bugs. If yes, it need to be added on the list.

**Comment by MrCK1** [comment]
Guess I forgot to mention earlier that "The Suffering: Ties that Bind" can be added here. See #1774 for details.

**Comment by gregory38** [comment]
@FlatOutPS2 
The PR #1843 seems to fix Smash Court Tennis Pro Tournament
![screenshot - 03052017 - 06 32 34 pm](https://cloud.githubusercontent.com/assets/1569559/23589729/b20d6c30-01d2-11e7-8f77-4c04125bfe4f.png)

Are those issues SW only ? Do we have a gs dump for them ?
```
ATV Quad Power Racing 2 - missing quads in SW mode
Arc The Lad: End Of Darkness - text balloon cursor cut-off in SW mode
```

**Comment by FlatOutPS2** [comment]
The Arc The Lad: End Of Darkness gsdump is included in the thread I linked: http://forums.pcsx2.net/Thread-GSDX-Software-mode-Bug-Report-Arc-The-Lad-End-Of-Darkness-Graphical-glitch

**Comment by gregory38** [comment]
Ok. ATV seems to be fine with the PR too. At least when I replay multiple time the dump, quads appear :)

**Comment by gregory38** [comment]
@FlatOutPS2 the dump expired.

ATV testcase is really interesting. My new code is working due to luck.

**Comment by FlatOutPS2** [comment]
Arc The Lad: End Of Darkness gs dump:
[Arc End Of Darkness - triangle icon partially hidden in SW mode.zip](https://github.com/PCSX2/pcsx2/files/819645/Arc.End.Of.Darkness.-.triangle.icon.partially.hidden.in.SW.mode.zip)

Isn't luck also the reason why several other games have been fixed by that PR? :p

**Comment by gregory38** [comment]
Nah I did my homework. I pushed a one line fix on master that fix a bad optimization. Hopefully it will fix multiple games.

**Comment by gregory38** [comment]
Holy cow, Arc is still broken. If you heard someone screamed, it was me :(

**Comment by gregory38** [comment]
It is a depth issue. I'm surprised that the HW render is kind of working.
Depth of the triangles of the ballon ranges from 0x7FFFFFF6 to 0x7FFFFFF7. But looking at the depth buffer, I can 0x80000000 values written.
The cursor uses 0x7FFFFFF6 as depth value. Maybe we need to round somewhere the depth. But I'm afraid it can't be fixed.

**Comment by gregory38** [comment]
Does anyone manage to reproduce the Zone of Ender issue. Report is quite old.

**Comment by FlatOutPS2** [comment]
> Does anyone manage to reproduce the Zone of Ender issue. Report is quite old.

The included dump still shows the issue with recent PCSX2 builds.

**Comment by gregory38** [comment]
@FlatOutPS2  Any particular setting ?

**Comment by FlatOutPS2** [comment]
No, just the default.

**Comment by gregory38** [comment]
I don't see it. There is a light flickering but nothing more.

**Comment by gregory38** [comment]
@FlatOutPS2 could you quickly test the PR for blood will tell. Maybe it is the same kind of bug. Or do you have it without any extra rendering thread.

**Comment by FlatOutPS2** [comment]
I see the patterns from the image in the bug report with all Software renderers, with or without extra renderering threads. Hardware mode is fine.

**Comment by gregory38** [comment]
![screenshot - 03132017 - 07 44 54 pm](https://cloud.githubusercontent.com/assets/1569559/23870084/8fde533c-0825-11e7-9ea8-adfe21ab138d.png)

Really strange. Or am I blind ?

**Comment by FlatOutPS2** [comment]
That's what the GS dump looks like in Hardware mode.

This is what I see in Software mode:
![sw](https://cloud.githubusercontent.com/assets/15942346/23870187/f17d5548-0825-11e7-94a2-18b35125d9c4.png)

**Comment by gregory38** [comment]
Ok I dumped all states I can see some bad frame buffer. However the 2 of them are memory content before draw. The draw itself is good on my side.

**Comment by gregory38** [comment]
@FlatOutPS2 Which instruction set ? Is your CPU compatible with AVX ?

**Comment by FlatOutPS2** [comment]
That's probably what I'm seeing then, it's not the first time I've had that. I also get dumps that are only a black screen in Hardware mode. So there's probably some difference between Linux and Windows(NVIDA and AMD?) on what we get see on screen.

My CPU is compatible with all supported instruction sets.

**Comment by gregory38** [comment]
Yeah maybe, the dump is one frame (maybe 2). With double/triple buffering, you might see the initial screen. 
```
I also get dumps that are only a black screen in Hardware mode
```
Sometimes, they work if you play then twice in a row (or it would flicker). Look at the Linux code the finished variable. Old dump was 2 frames which isn't enough due to interlacing and other niceties. Recent dump are 4 frames much better.

**Comment by gregory38** [comment]
@turtleli 
Pseudo and I  have found a strange GCC 4.9 bug with AVX2. I'm curious if you have it on recent version too.

C function (last line):
```
void GSDrawScanline::BeginDraw(const GSRasterizerData* data)
{
	memcpy(&m_global, &((const SharedData*)data)->global, sizeof(m_global));

	if(m_global.sel.mmin && m_global.sel.lcm)
	{
		GSVector4i v = m_global.t.minmax.srl16(m_global.lod.i.extract32<0>());//.x);
```
GCC AVX2 ASM
```
8ed: vmovdqa xmm0,XMMWORD PTR [esi+0x160]
8f5:   vmovdqa xmm3,XMMWORD PTR [esi+0xb0]
8fd:   vpsrlw xmm0,xmm3,xmm0
```

Clang AVX2 ASM
```
161:   vmovdqa ymm0,YMMWORD PTR [esi+0x160]
169:   vpxor  xmm1,xmm1,xmm1
16d:   vpblendw xmm0,xmm1,xmm0,0x3
173:   vmovdqa xmm1,XMMWORD PTR [esi+0xb0]
17b:   vpsrlw xmm0,xmm1,xmm0
```
The issue is that the shift counter (gcc:xmm3/clang:xmm1) is 64 bits. Clang clears the upper 32 bits with the `vpblendw` instruction but gcc don't. GCC shift will be too big.

**Comment by turtleli** [comment]
GCC 6.3 AVX2
```
5d348:	vmovdqa ymm0,YMMWORD PTR [ebx+0x160]
5d350:	vmovdqa xmm3,XMMWORD PTR [ebx+0xb0]
5d358:	vpsrlw xmm0,xmm3,xmm0
```

**Comment by gregory38** [comment]
Thanks you. Not better, interested enough the load is now 256 bits... I need to check if we can do a 32 bits load instead. Otherwise I will stick a volatile in the middle.

**Comment by FlatOutPS2** [comment]
This now also applies here: https://github.com/PCSX2/pcsx2/issues/804

**Comment by MrCK1** [comment]
Added "The Suffering: Ties That Bind" to the list - #1929

**Comment by atomic83GitHub** [comment]
You can add Beyond Good and Evil, the game don't render the water's color as it should in some places (basicaly open world environnement), it is red instead of black (I will post a screenshot later) and in some places, corners have a red layer covering them (again I will post a screenshot because it's pretty hard to explain that).

**Comment by FlatOutPS2** [comment]
@atomic83GitHub You already added a screenshot here: https://github.com/PCSX2/pcsx2/issues/1986

**Comment by atomic83GitHub** [comment]
Yes but the issue is a bit different under the software mode :).

**Comment by FlatOutPS2** [comment]
>Yes but the issue is a bit different under the software mode.

That doesn't matter much, you already added a gsdump to that issue.

> Edit: you wrote beyong instead of beyond :).

Fixed 😛

**Comment by FlatOutPS2** [comment]
@gregory38 I found another Software only issue. The bottom left of the arm is missing during a close up in a cutscene of Silent Hill 3. None of the hardware renderers are affected. It's not a (recent) regression, it goes back to at least before PCSX2 v1.2.1.

[Silent Hills 3 SW issue.zip](https://github.com/PCSX2/pcsx2/files/1647318/Silent.Hills.3.SW.issue.zip)

**Comment by LoStraniero91** [comment]
Two games by In Utero, **Evil Twin: Cyprien's Chronicles** and "**The Shadow of Zorro**" (it should be noted that Zorro only works properly with Super VU1) , which probably use the same engine, have a graphical bug in software mode not present in HW:

textures on most elements (especially characters) will look very blurry and low-res in SW, switching to HW fixes the issue. Evil Twin seems to suffer the most, with missing graphic too.

**Zorro SW**
![zorro sw](https://user-images.githubusercontent.com/29802222/36812778-94f06a00-1cd2-11e8-8ae1-2ed0d0893ae0.jpg)
**Zorro HW**
![zorro hw](https://user-images.githubusercontent.com/29802222/36812791-9ad57d7a-1cd2-11e8-9c04-49f42a40788d.jpg)

**Evil SW**
![evil sw](https://user-images.githubusercontent.com/29802222/36813115-c4bbb7de-1cd3-11e8-96ed-295f67e3358e.jpg)
![evil 2 sw](https://user-images.githubusercontent.com/29802222/36813235-306f94c8-1cd4-11e8-9a35-2291acc7082d.jpg)

**Evil HW**
![evil hw](https://user-images.githubusercontent.com/29802222/36813138-db27dd04-1cd3-11e8-9ebc-02faa5a21fb6.jpg)
![evil 2 hw](https://user-images.githubusercontent.com/29802222/36813238-3333e290-1cd4-11e8-9a13-d0c979e44651.jpg)

**Comment by LoStraniero91** [comment]
These were tested with the lastest git, no speedhack at all (aside for Zorro which needs Super VU1).

**Comment by FlatOutPS2** [comment]
> These were tested with the lastest git, no speedhack or gamefixes at all (aside for Zorro which needs Super VU1).

That's odd. The title bar info in your screenshots is missing data that should be there with the latest git.

**Comment by MrCK1** [comment]
I'm adding Wallace & Grommit: Curse of the Were-Rabbit. Textures are broken in SW when mipmapping is enabled, only turning mipmapping off will resolve it. Hardware mode is fine however.

**Comment by LoStraniero91** [comment]
Wanted to add another issue that's happening in the game **Alone in the Dark [SLES-54883]**, very minor issue but it's still noticable if you played the game on real hardware.
Basically, only the D3D11 HW gets it right, the problem is that it introduces other graphical glitches.

The issue is that on the top-left corner, a model of the PS2 controller appears telling you which button to press "as a tutorial" to learn the game mechanics. A small circle will "focus" on said button and what's outside it should be "hidden". Instead, in both OGL HW and SW this doesn't happen and you still see the full model of the controller.

![OGL HW](https://user-images.githubusercontent.com/29802222/62768467-3267c400-ba97-11e9-9983-6e63d06edb65.jpg)
![SW](https://user-images.githubusercontent.com/29802222/62768475-35fb4b00-ba97-11e9-8d5f-ad99c4b4d3a3.jpg)
![D3D11 HW](https://user-images.githubusercontent.com/29802222/62768483-385da500-ba97-11e9-9506-a102cffde755.jpg)

**Comment by atomic83GitHub** [comment]
A GSdump of that screen wound be helpfull, can you make one?

**Comment by LoStraniero91** [comment]
Here's a GSdump of the issue with all 3 renderers.

[D3D11 HW.zip](https://github.com/PCSX2/pcsx2/files/3486295/D3D11.HW.zip)
[OGL HW.zip](https://github.com/PCSX2/pcsx2/files/3486296/OGL.HW.zip)
[SW.zip](https://github.com/PCSX2/pcsx2/files/3486297/SW.zip)

**Comment by piau9000** [comment]
#2427
Ridge Racer V (car shadows are not rendered properly).

**Comment by tadanokojin** [comment]
Ridge Racer will be sorted with https://github.com/PCSX2/pcsx2/pull/3263.

**Comment by HelicopterP** [comment]
Silent Hill 3 is fixed by #3433

**Comment by refractionpcsx2** [comment]
Thanks :) I've ticked that one off the list, along with Formula One 2004 which I believe is also fixed.

**Comment by ichee** [comment]
[#3485](https://github.com/PCSX2/pcsx2/issues/3485)

PlayStation 2 logo drops to bottom of screen before disappearing.

Rendered properly with gsdx-hw.

**Comment by LoStraniero91** [comment]
**WRC: Rally Evolved [SCES-53247] [CBBC2E7F]
PCSX2 1.7.0.-dev-604-g9d4337b7e**
Sun has graphical glitches in SW mode, in HW mode seems fine. It doesn't happen in hood and cockpit view. This is Montecarlo stage, it also happens in other stages.

![Immagine](https://user-images.githubusercontent.com/29802222/99186955-2071d800-2754-11eb-9262-1baa810f7383.png)
![Immagine](https://user-images.githubusercontent.com/29802222/99186985-4303f100-2754-11eb-8b8f-76c47de1e9e3.png)

[snaps.zip](https://github.com/PCSX2/pcsx2/files/5542488/snaps.zip)

**Comment by prafullpcsx2** [comment]
Regarding Arc The Lad

It was broken here:-

https://github.com/PCSX2/pcsx2/commit/ee9c9ac8f30ff9157bfc759a36fd372bf9809019

**Comment by LoStraniero91** [comment]
> Two games by In Utero, **Evil Twin: Cyprien's Chronicles** and **The Shadow of Zorro** (it should be noted that Zorro only works properly with Super VU1) , which probably use the same engine, have a graphical bug in software mode not present in HW:
> 
> textures on most elements (especially characters) will look very blurry and low-res in SW, switching to HW fixes the issue. Evil Twin seems to suffer the most, with missing graphic too.
> 
> **Zorro SW** ![zorro sw](https://user-images.githubusercontent.com/29802222/36812778-94f06a00-1cd2-11e8-8ae1-2ed0d0893ae0.jpg) **Zorro HW** ![zorro hw](https://user-images.githubusercontent.com/29802222/36812791-9ad57d7a-1cd2-11e8-9c04-49f42a40788d.jpg)
> 
> **Evil SW** ![evil sw](https://user-images.githubusercontent.com/29802222/36813115-c4bbb7de-1cd3-11e8-96ed-295f67e3358e.jpg) ![evil 2 sw](https://user-images.githubusercontent.com/29802222/36813235-306f94c8-1cd4-11e8-9a35-2291acc7082d.jpg)
> 
> **Evil HW** ![evil hw](https://user-images.githubusercontent.com/29802222/36813138-db27dd04-1cd3-11e8-9ebc-02faa5a21fb6.jpg) ![evil 2 hw](https://user-images.githubusercontent.com/29802222/36813238-3333e290-1cd4-11e8-9a13-d0c979e44651.jpg)

After 3 years I've found out that by setting EE Clamping to Extra+Preserve Sign textures are fixed in SW mode.

**Comment by refractionpcsx2** [comment]
> > Two games by In Utero, **Evil Twin: Cyprien's Chronicles** and **The Shadow of Zorro** (it should be noted that Zorro only works properly with Super VU1) , which probably use the same engine, have a graphical bug in software mode not present in HW:
> > textures on most elements (especially characters) will look very blurry and low-res in SW, switching to HW fixes the issue. Evil Twin seems to suffer the most, with missing graphic too.
> > **Zorro SW** ![zorro sw](https://user-images.githubusercontent.com/29802222/36812778-94f06a00-1cd2-11e8-8ae1-2ed0d0893ae0.jpg) **Zorro HW** ![zorro hw](https://user-images.githubusercontent.com/29802222/36812791-9ad57d7a-1cd2-11e8-9c04-49f42a40788d.jpg)
> > **Evil SW** ![evil sw](https://user-images.githubusercontent.com/29802222/36813115-c4bbb7de-1cd3-11e8-96ed-295f67e3358e.jpg) ![evil 2 sw](https://user-images.githubusercontent.com/29802222/36813235-306f94c8-1cd4-11e8-9a35-2291acc7082d.jpg)
> > **Evil HW** ![evil hw](https://user-images.githubusercontent.com/29802222/36813138-db27dd04-1cd3-11e8-9ebc-02faa5a21fb6.jpg) ![evil 2 hw](https://user-images.githubusercontent.com/29802222/36813238-3333e290-1cd4-11e8-9a13-d0c979e44651.jpg)
> 
> After 3 years I've found out that by setting EE Clamping to Extra+Preserve Sign textures are fixed in SW mode.

This has now been resolved in the GameDB

**Comment by LoStraniero91** [comment]
1.7.2063
Metal Gear Solid 3: Subsistence has alignment issues with the boxes in SW, looks fine in HW.
[Immagine](https://user-images.githubusercontent.com/29802222/142915210-7443787c-e802-405c-92ee-9e4f9f7e3f6d.png)
[Immagine2](https://user-images.githubusercontent.com/29802222/142915280-525e51e1-be07-4f8c-9092-fce192158d3a.png)

**Comment by personaone** [comment]
FFX - top left corner messed up with the SW renderer, thought i might throw this in here
![gs_20220129094723](https://user-images.githubusercontent.com/8123295/151654696-566fc530-59df-46a1-856e-c0eb11c34850.png)

**Comment by RedDevilus** [comment]
Because on HW it's using a CRC hack.

**Comment by personaone** [comment]
Tales of Legendia - banding horizontal lines that don't appear on real hardware.

![gs_20220206135209](https://user-images.githubusercontent.com/8123295/152681724-4dbf2a47-747b-4a8f-9aea-bc3584fd2b71.png)

**Comment by MrCK1** [comment]
> Tales of Legendia - banding horizontal lines that don't appear on real hardware.
> 
> ![gs_20220206135209](https://user-images.githubusercontent.com/8123295/152681724-4dbf2a47-747b-4a8f-9aea-bc3584fd2b71.png)
> 
> 

Try turning off dithering if you have it enabled

**Comment by LoStraniero91** [comment]
> **WRC: Rally Evolved [SCES-53247] [CBBC2E7F] PCSX2 1.7.0.-dev-604-g9d4337b7e** Sun has graphical glitches in SW mode, in HW mode it's fine but that's because the lense flare effect is not correctly emulated. It doesn't happen in hood and cockpit view. This is Montecarlo stage, it also happens in other stages.
> 
> ![Immagine](https://user-images.githubusercontent.com/29802222/99186955-2071d800-2754-11eb-9262-1baa810f7383.png) ![Immagine](https://user-images.githubusercontent.com/29802222/99186985-4303f100-2754-11eb-8b8f-76c47de1e9e3.png)
> 
> [snaps.zip](https://github.com/PCSX2/pcsx2/files/5542488/snaps.zip)

Fixed in the recent builds.

**Comment by AhayriSG** [comment]
NASCAR 08 SLUS21639 crashing with SW renderer
Details;
https://github.com/PCSX2/pcsx2/pull/5980#issuecomment-1140241534
https://github.com/PCSX2/pcsx2/pull/5980#issuecomment-1140437711
https://github.com/PCSX2/pcsx2/pull/5980#issuecomment-1140439373

**Comment by AhayriSG** [comment]
> I don't think that's true anymore, we fixed it.
> 
> You can find a lot of comments saying things are broken if you search github for them, doesn't mean it's still true.

![nascar](https://user-images.githubusercontent.com/59465544/180001094-c9d1ba58-98f0-4613-933a-3465b8fe3692.gif)

**Comment by AhayriSG** [comment]
> What the heck, I was sure we fixed that :/

v1.7.3107, same settings;
![nascarss](https://user-images.githubusercontent.com/59465544/180282175-3cd4d036-9666-4e31-9d3e-6fc20c3f982d.gif)
😵‍💫

**Comment by refractionpcsx2** [comment]
Yeah I can see locally it's not fixed, I think I know why, the question is how to handle it

**Comment by refractionpcsx2** [comment]
NASCAR will be dealt with in #6683

**Comment by personaone** [comment]
> 

Hey - was anyone able to reproduce this Tales of Legendia issue with the lines here? It's still valid as of today, just tried again

**Comment by refractionpcsx2** [comment]
yes, it's reproducable.

**Comment by refractionpcsx2** [comment]
Tested Dragon Quest & Final Fantasy in Itadaki Street Special on hardware with a (broken) dump from PCSX2, and the board is there. So confirmed GS issue.
![image](https://user-images.githubusercontent.com/6278726/184516413-a7c5bfe4-7bea-4aea-8f74-8c05ae398171.png)

Also tested Pride FC, text is still missing, so confirmed core issue (most likely)

![image](https://user-images.githubusercontent.com/6278726/184516404-8efbcb26-9074-4469-b510-12e624bfe6d8.png)

**Comment by personaone** [comment]
Interesting SW glitch in Wrath of Heaven (US) check out the weird 
![Tenchu 3 - Wrath of Heaven_SLUS-20397_20221203164330](https://user-images.githubusercontent.com/8123295/205449558-4a78cc1f-ca37-496d-bde2-b84b225edecd.png)
![Tenchu 3 - Wrath of Heaven_SLUS-20397_20221203164319](https://user-images.githubusercontent.com/8123295/205449560-ddbf1a30-7c04-477d-880d-05c53f5781ed.png)
glitchy rectangles I marked in red. They sort of shimmer when you pan the camera around in this area :D

**Comment by Mrlinkwii** [comment]
@personaone can you post a gs dump

**Comment by personaone** [comment]
[Tenchu 3 - Wrath of Heaven_SLUS-20397_20221203192037.gs.zip](https://github.com/PCSX2/pcsx2/files/10147076/Tenchu.3.-.Wrath.of.Heaven_SLUS-20397_20221203192037.gs.zip)
here you go

**Comment by benderscruffy** [comment]
v1.7.4207
still happens in Mercenaries 1 and 2
![Mercenaries - Playground of Destruction_SLUS-20932_20230311170822](https://user-images.githubusercontent.com/2696404/224475741-64b7435c-1919-431d-9756-c1af69e59e3c.png)
[Mercenaries - Playground of Destruction_SLUS-20932_20230311170822.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/10948069/Mercenaries.-.Playground.of.Destruction_SLUS-20932_20230311170822.gs.zst.zip)
![Mercenaries 2 - World in Flames_SLUS-21650_20230311170645](https://user-images.githubusercontent.com/2696404/224475749-94edf10f-6472-4c61-89f9-0a4ec16143b7.png)
[Mercenaries 2 - World in Flames_SLUS-21650_20230311170645.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/10948070/Mercenaries.2.-.World.in.Flames_SLUS-21650_20230311170645.gs.zst.zip)
![Mercenaries 2 - World in Flames_SLUS-21650_20230311170704](https://user-images.githubusercontent.com/2696404/224475756-269e1175-2236-4bc1-95df-fa16d160fb68.png)
[Mercenaries 2 - World in Flames_SLUS-21650_20230311170704.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/10948072/Mercenaries.2.-.World.in.Flames_SLUS-21650_20230311170704.gs.zst.zip)
![Mercenaries 2 - World in Flames_SLUS-21650_20230311170712](https://user-images.githubusercontent.com/2696404/224475758-2b726a58-4de7-4e62-8403-04db91b92d3b.png)
[Mercenaries 2 - World in Flames_SLUS-21650_20230311170712.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/10948073/Mercenaries.2.-.World.in.Flames_SLUS-21650_20230311170712.gs.zst.zip)

**Comment by JordanTheToaster** [comment]
> v1.7.4207 still happens in Mercenaries 1 and 2

It's fixed by pre round.

**Comment by benderscruffy** [comment]
> > v1.7.4207 still happens in Mercenaries 1 and 2
> 
> It's fixed by pre round.

and where about do i find this please

**Comment by personaone** [comment]
> FFX - top left corner messed up with the SW renderer when entering battle, thought i might throw this in here, doesn't happen with vulkan ![gs_20220129094723](https://user-images.githubusercontent.com/8123295/151654696-566fc530-59df-46a1-856e-c0eb11c34850.png)

I just checked this again, looks like it was fixed on SW - not sure which commit though, I'm on latest - can anyone confirm? That's pretty awesome!

**Comment by refractionpcsx2** [comment]
> I just checked this again, looks like it was fixed on SW - not sure which commit though, I'm on latest - can anyone confirm? That's pretty awesome!

yes that was fixed in #9302

**Comment by Mrlinkwii** [comment]
Largo Winch- Empire Under Threat  has an issue in SW mode broken shadows 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/9f3a1762-b099-4546-9630-3722485f8165)
![image](https://github.com/PCSX2/pcsx2/assets/17685135/db2a6815-84d1-47cb-be3a-3e813bb0c441)

[SW_largo.zip](https://github.com/PCSX2/pcsx2/files/14875944/SW_largo.zip)
