### ISSUE TITLE
Syphon Filter: TOS - Selected weapon icon drawn in incorrect order

### ISSUE THREAD

**Issue by ilag11111** [PCSX2/pcsx2#1602]
-Game Title: Syphon Filter: The Omega Strain NTSC - SCUS-97264
-PCSX2 version: 866173a and newer
-PCSX2 options: Defaults, no settings modifications affect the issue
-Plugins used: GSdx, SPU2-X, OnePad
-Plugin settings: GSdx OGL hardware and software renderers.

-Description: The selected weapon icon is drawn partially behind the transparent blue background it's supposed to be drawn above.  This happens in both software and hardware, with hardware having significantly more defects.
Example image: https://s21.postimg.org/b5zy45qev/image.png

-How to replicate: Start any level, and once you have control over the character, inspect the icon in the bottom right corner.  If portions are blue or missing, the issue is present.  It's easiest to see by switching to unarmed and looking at the hands icon.

-Last known version to work: fb2182d

-PC specifications: CPU: AMD Phenom II X4 965 GPU: EVGA Nvidia GTX 680 FTW+ OS: Ubuntu 16.04

-Other Comments
To be fair, the icon wasn't drawn completely correctly before 866173a.  Certain weapons such as the MDS A4 had parts that were drawn incorrectly - though consistently between hardware and software, but most were fine.  Now, it seems almost every weapon has issues.

**Comment by FlatOutPS2** [comment]
The cut off fingers issue appears between builds 1126 and 1132, which is the alpha test improvement merge. The issue does not affect Direct3D renderers though.

**Comment by gregory38** [comment]
Potentially pr #1593 will improve the situation. However it could be due to the rounding bug of the vertex trace of the Z value. Too bad that I threw the code.

A gs dump will be nice to spot the exact regression.

**Comment by FlatOutPS2** [comment]
I tried PR 1593, but it had no effect on the issue.

[Syphon Filter The Omega Strain HUD issues.zip](https://github.com/PCSX2/pcsx2/files/505105/Syphon.Filter.The.Omega.Strain.HUD.issues.zip)

Contains 2 GS Dumps. One is the missing fingers, which are missing in OGL HW.
The other is the gun. Which is almost completely blue in OGL HW, partially blue in SW modes, but fine in DX HW modes...

**Comment by gregory38** [comment]
missing finger is related to ATE. However the draw call (number 853) wasn't impacted by the new change.

By the way the game triggers the following assertion:
```
ASSERT(m_vt.m_min.p.z > max_z); // sfex capcom logo
```
Maybe it could explain the strange behavior on various renderer.

Oh it seems a change was introduced in Dx. I don't see the equivalent of
```
	vs_cb.DepthMask = GSVector2i(max_z, max_z);
```
=> vs_sel.bppz ?

**Comment by gregory38** [comment]
Yep, old code only enable DepthMask when m_vt.m_max.p.z > max_z. My new code always enable it, it is bad idea. I will change it.

**Comment by gregory38** [comment]
Ok tell if it is better. Sw renderer is likely bad because there is a depth overlow. We don't care on GPU as buffer isn't linked to the GS memory.

**Comment by FlatOutPS2** [comment]
The handgun and fingers are now fixed in OGL Hardware. @ilag11111 Can you check the other weapons?

**Comment by ilag11111** [comment]
Testing revision 1b8d6a3

OGL Hardware: Checked a few items.  Appears to work just like fb2182d, so regression fixed.  Which means there's still a few select weapons with blue or missing pieces such as the MDS A3 on weapons aside from a select few such as the MDS A3.
GS dump with screenshot: [SFTOS_MDSA4_imperfect.zip](https://github.com/PCSX2/pcsx2/files/509616/SFTOS_MDSA4_imperfect.zip)

OGL Software: Still messed up.  Though I found it funny that the VSS-DU looks like it has a CS:GO skin applied to it in software, while it appears correctly in Hardware.
GS dump with screenshot: [SFTOS_VSSDU_goodhardbadsoft.zip](https://github.com/PCSX2/pcsx2/files/509615/SFTOS_VSSDU_goodhardbadsoft.zip)

**Comment by gregory38** [comment]
The thing is hw renderer can't emulate properly the alpha test effect (due to gpu limitation). However it supports a full range of depth.
On the other hand, the sw render support correctly the alpha test effect but choke on depth value above the maximum allowed. I think that we're above the max due to VU/FPU rounding.

**Comment by MrCK1** [comment]
As of latest git (v1.5.0-dev-2241-g18ea36adc) all HW renderers work fine - GS dumps check out as well. SW renderers are still broken.
