### ISSUE TITLE
Valkyrie Profile 2: Silmeria [PAL-E] - A/V desyncs,  hard lock during FMV playback

### ISSUE THREAD

**Issue by trostboot** [PCSX2/pcsx2#1634]
**_PCSX2 version:**_
PCSX2 1.5.0-20161020041703

**_PCSX2 options:**_
Defaults, no speedhacks

**_Plugins used:**_
GSdx AVX2 D3D11 SW, Pokopom, SPU2-X (also tested with ZeroSPU2)

**_Description of the issue:**_
PAL versions of Valkyrie Profile 2 (version tested is PAL-E, SLES-54644, CRC 04CCB600, image md5 bb2e4fe43daae8b85bcbe4e69e11a9e2) suffer from severe audio/video desync during FMV playback. Audio is played back at normal speeds, video is played back faster and suffers from additional heavy stuttering.
Furthermore, if the intro FMV cinematic isn't skipped, the game will lock up at the end. 

**_How to reproduce the issue:**_
1. Boot up a PAL version of Valkyrie Profile 2

**_Last known version to work:**_
None. As far as I can tell, this never worked. There's the odd thread on the forums mentioning it going back many years, but usually alongside other issues so it got sidelined or classified as PEBKAC.

**_PC specifications:**_
Intel i5-4690k, AMD R9 270X, 16GB RAM, Win10 x64 14393)

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/544998/emuLog.txt)

**Comment by FlatOutPS2** [comment]
Go to Config > Audio (SPU2) > Plugin Settings, and set **Synchronizing Mode** to "Async Mix". Then try the FMVs again.

**Comment by trostboot** [comment]
Already did. Sorry, should have been more clear. Changing sync modes does nothing. And as I stated, it also happens with ZeroSPU2.

**Comment by willkuer** [comment]
Maybe try different delaycycle in spu2-x.ini. Something like 0-10. But probably unrelated if sound is working correctly.

**Comment by trostboot** [comment]
Yeah, that doesn't change anything. I tried a few other settings just to be sure (EE/IOP interpreters, EE timing hack), but it doesn't make any difference.

**Comment by jcdenton2k** [comment]
Try regular memory card files instead of memory card folders.  Also make sure you are using Safe or Safest presets and see what happens.  I'll see about getting someone with the game to help me test something on my end here.

**Comment by trostboot** [comment]
The issue predates memory card folders by years and years. I tried it anyway to be sure, it has no effect.

It's the English version, aka UK. Relevant serial and hashes are already in the first post.

**Comment by jcdenton2k** [comment]
So here's the redump link:  http://redump.org/disc/4110
I'm gonna do some quick testing now.

**Comment by trostboot** [comment]
There's a difference between real-time in-game cutscenes and FMVs. There are no FMVs in the Lost Forest. I'm talking specifically about FMVs, and the hard lock that occurs happens at the very end of the opening cinematic (i.e., the one that plays right after you boot up the game, not the one that starts after you hit New Game).

Are you saying the game did not lock up after that FMV? Because it reliably 100% of the time did for me.

**Comment by jcdenton2k** [comment]
No it didn't lock up for me for any FMVs or in-game cutscenes.

**Comment by ramapcsx2** [comment]
The problem is probably the H/V Sync timings. If so, it can probably be made to work better by switching to PAL60 mode (hold X and Triangle on bootup).

**Comment by trostboot** [comment]
I'm fairly certain VP2 PAL doesn't support that (or progressive scan for that matter, unlike the NTSC releases).
Triangle + X just brings up an aspect ratio choice. I'll double-check when I get home from work, maybe I'm misremembering.

**Comment by trostboot** [comment]
Yeah, it doesn't have support for any other video modes.

Also, WRT the lock up, I re-tested the opening FMV again with fresh, untouched portable installs of 1.4.0 and 1.0.0 with default configs, and it froze again on both. Just be to super extra clear, it happens after that FMV plays, right where it normally loads into the title screen. 
I.e., boot up the game and then never touch a single button. @jcdenton2k Could you re-test it with a fresh 1.4.0 install?

**Comment by trostboot** [comment]
(using 1.5.0-dev-1764, but also seems to apply to 1.4.0)
EE cyclerate -1 fixes the freeze. EE cyclerate -2 or lower fixes both timing and the freeze. Not very practical of course, but maybe it's helpful to know.

**Comment by MrCK1** [comment]
Anybody like to test this again before closing? EE cyclerate could be added to GameDB later if necessary.

**Comment by trostboot** [comment]
Freeze and desync still happen on latest git. I don't see how this can be closed, the EE cyclerate changes are not a practical workaround, and most certainly shouldn't be added to the GameDB entry. For one, it's not been tested outside of the opening cutscene, and for another, VP2 already pushes the hardware.

**Comment by MrCK1** [comment]
OK, thanks for re-testing.

**Comment by ramapcsx2** [comment]
Getting better with each tick towards a slower EE hints at this being a stalling problem.
Real hardware will probably stall for a few EE cycles on some conditions (possibly in IPU DMA?) and we do not.

**Comment by mikazl57** [comment]
Hello !

Any news about this bug ? I have  the same A/V issues in FMV with the PAL French Version.

Thks

Build :pcsx2-v1.5.0-dev-3039-g1414d64b1-windows-x86

**Comment by ramapcsx2** [comment]
I think this improved with the WiP VSync timing fix, at least for progressive mode.
Real hardware has issues with the FMV cutscenes as well, by the way.

**Comment by trostboot** [comment]
There is no progressive mode in the PAL release.
And could you elaborate on issues on real hardware? I loaded up the English PAL version just now to have a look, and the opening FMV plays fine, it's in sync and the game doesn't blackscreen and freeze at the end like on PCSX2. Only noticed what seemed to be two very short audio dropouts that don't happen using emulation.

**Comment by ramapcsx2** [comment]
Yeah, the audio tends to be skippy on real hardware. It's not a lot but you notice it when looking for it.
I only tested the NTSC release, where timings are different and the progressive mode is available.

So I'm thinking this might be related to the VSync timing fix, even if yours is the PAL version.
The game's code base is surely the same, and is known to be borderline for the NTSC release.

**Comment by trostboot** [comment]
Let's put it this way, I've played through the NTSC release at least once fully on PCSX2 a good while ago, and even before that it's a game I mucked around in through the years. I never noticed any issues with the FMVs, despite using the EE cyclerate increases to smooth out in-game performance. I haven't noticed anything borderline about it.
It never occured to me to check how it plays in interlaced mode, but I did that just now and it works fine.

That's why I made sure to mention it's the PAL version that suffers from this issue, because as far as I can tell and remember throughout the years, the NTSC version was fine.

**Comment by ramapcsx2** [comment]
Well, if you've still got the NTSC version, try running the intro. 
Watch and listen carefully, the glitches will happen even before they first speak.
Try it in 480p as well, and see if you can spot any jerky motion or audio oddities.

I get reliable skipping in the first few seconds here (both modes), and iirc, this is fixed with the new VS timing.

The same skipping can be observed on a SCPH-90002 machine, though less pronounced and further into the FMV.

**Comment by trostboot** [comment]
I'm more inclined to believe those audio glitches are in the source audio. It only happens on the original US disc, not with the undub patch applied. They're also in the exact same spot when using real hardware (SCPH-39004 for me). Either way, it would be weird if those changes would do anything about these glitches, because as it is, they're replicated accurately.
Here, take a look:
![vp2audio](https://user-images.githubusercontent.com/17594477/56322270-dc2de880-6168-11e9-9cb9-94400f7490c0.png)
The top one is the US release on PCSX2, captured using the internal recording function.
The middle is the same version running on my PS2, captured using the S/PDIF out.
The bottom is the English PAL release, also captured from my PS2.

Either way, it sounds like you haven't had a chance to see the issues in the PAL version for yourself, but they're much more severe than this. Audio and video are completely out of sync (several seconds at the best of times), the video jitters heavily, and of course it blackscreens and freezes at the end.

I tried to have a look at it with the vsync timing changes, but VS made a fuss and it's too late now to try and wrestle with that particular beast right now. If you have a build of that branch somewhere, I'd be glad to take a look.

**Comment by ramapcsx2** [comment]
To make sure: You disabled all cycle speedhacks, right?
I see just one dropout in your NTSC capture, but here I get several right from the beginning.

Yeah, I need to check the PAL disk. But finding one.. :p

**Comment by trostboot** [comment]
Of course, all speedhacks disabled, software rendering, default EE/IOP/VU settings.

You're right in that you can't see all of the dropouts up there, the timeline ended up being a bit too long. But there's more and they are identical between real hardware and emulation.
Listen for yourself: [vp2audio.zip](https://github.com/PCSX2/pcsx2/files/3093692/vp2audio.zip)

I think they screwed up the English audio in the NTSC release and fixed it for the PAL conversion. Either way, I don't think it's related to this issue here.

**Comment by ramapcsx2** [comment]
The desync is something to look into. I just need the VP2 PAL intro but that game is huge and expensive to buy these days ><

**Comment by trostboot** [comment]
Would a blockdump work for you? Would come in at around 220mb, FMV and all.

**Comment by ramapcsx2** [comment]
Would help, yep :p 
It should include the entire intro and also the main menu music is streamed from disk.
I think it'll loop to the FMV automatically.
If you test it and there are no missing blocks notices, that'd be perfect!

**Comment by trostboot** [comment]
[Here you go.](https://drive.google.com/file/d/1AS87vEb7f641Q1FXFDeqsG2-J6xXDD8z)
Entire intro + main menu.

**Comment by ramapcsx2** [comment]
Great, this works well. I can see how it screws up badly right away.

**Comment by ramapcsx2** [comment]
And yea, I'm almost sure this is the same timing calculations issue as with the NTSC version.
I think they're doing some kind of synchronization within VBlank, and that this is a tight fit even on real hardware.
The video gets fixed by underlocking the EE, introducing the same audio glitches as on NTSC but fixing the sync.
The code is the same, but our PAL cycles are different enough to shift the problem from audio skips to video descync.
It'll all be in the VBlank handler anyway.

**Comment by mikazl57** [comment]
I made a video some time ago with this problem if it can help with the real DVD PAL:
[https://www.youtube.com/watch?v=zFkQ8YZKwlk&feature=youtu.be](url)

**Comment by mikazl57** [comment]
Same bug on new version of PCSX 1.6.0

**Comment by refractionpcsx2** [comment]
Since some vsync and spu2 stuff has been changed since 1.6, can you confirm if this still happens and is there and easy way to replicate this? like does the intro movie do it?

**Comment by trostboot** [comment]
Yeah, same issue still on PCSX2 1.7.0-20201211105624.
Intro movie does it, yeah (the blockdump up above includes it). Hardcoded subs, so it's very easy to tell right from the start. Letting it play out in full will then cause the game to lock up.

**Comment by refractionpcsx2** [comment]
ok thanks for the update :)

**Comment by refractionpcsx2** [comment]
Okay I looked in to this and from what I can tell when comparing to my PS2, our counters, HSYNC and VSYNC counters are accurate, however the game wants HSYNC to be counted 5% faster, which would be an incorrect value.  I'm not sure if the problem is this or something else causing the timing to be out, since slowing down the EE (setting the slider to -1, or -2, i forget) seems to also fix the sync and all that does is makes the EE instructions take longer.

so it's possible they have timed something on the EE and it's not matching up, so this could be a real pig to fix correctly, but I'm pretty confident it isn't a counter issue.

**Comment by refractionpcsx2** [comment]
According to #6545 this also happens in 1080i mode.

**Comment by trostboot** [comment]
@Uzarkis  PAL version still suffers from the issues described here. I suggest procuring a copy of the US version if you want to play it.

**Comment by mikazl57** [comment]
Hello, some news about this issue ? 
I have tested the new version 2.3.75 and the A/V desyncs is still here.
On SLES-54645 french pal version.
Can't play on us version because i don't speak english.

**Comment by refractionpcsx2** [comment]
Okay I kinda did some messing around and these are the ramblings from what I found


setting the loop at 002be1ac to beq zero zero the video is smooth with no more stutters/desync (not a solution as it'll trigger the anti-cheat if patched)
```
## None of the following 9B#### addresses will be relevant on your run, this is a randomly generated memory address! once I got base values of 9B0540, next time i got 9B0B40 another time I got 9B0040 (below), these all get offset by 0x63 in to some kind of struct
{
009B00A3 seems to hold a value it wants to be zero but is set to 1 after a DMA packet is prepared
also checks 009b00a3 at 0022162C

set to zero at 0021EB80, 002213A4
stores actual value of 1 at 002BEA0C which is just after DMA packet assembly function located at 0x2BC430 (dma packet ready??)
Maybe there's some DMA signal not being set

set at 002bea00

00B0FB80 is checked for not zero and that seems to be set by 002BCBE4 to a double of 30000700 00CD8D00 which is some kind of DMA packet assembly (mentioned above) (REF packet for 0x700qw)
002BCC20 clears 00B0FB80
}
```

So yeah I'm not sure exactly what's going on, if it's not getting a signal it wants and panicking, so resorting to reading the hsync counter and trying to play catchup with the frames, causing it to go wildly out of time, or what. But I do think it expects this 9B address + 0x63 to be zero when it hits this code to say "everything has finished" or "a new frame has started", not sure which it means.

I can also say this loop I said to beq zero zero at 002be1ac, ,it doesn't always not take it, sometimes it falls through and that's when it gets in to waiting for the hsync count to be 0x120/288.  There is also a situation it seems where that could be 0x240/576, I'm not sure what.

It's late now, maybe @Goatman13 will want to take a punt at it, I've attached an EE memory dump used for reference for the EE code.

[VP2-PAL-eeMemory.zip](https://github.com/user-attachments/files/32036766/VP2-PAL-eeMemory.zip)

**Comment by Goatman13** [comment]
No idea about that one. It seems like semi backward compatible PS3 have hidden patch related (or not) to that issue, they force $at to 0 on 0x2B9808 (by hook in recompiler, to not alter memory). This fail in pcsx2 but maybe it will give some hint.

I accidentally found out that delaying certain VIF1 transfer fixes it too. 
Just in case, transfer takes 0xE00 cycles and needs at least 3x that to fix things. 

```c
	if (CHECK_EETIMINGHACK && n == DMAC_VIF1 && ecycle == 0xE00)
		ecycle *= 3;
```

Obviously, it's not a fix or anything, but maybe will give some hint what's going on 
Hsync stuff looked promising, but I think that it's not real issue here. Probably looping there just allowed other stuff to finish, and that other stuff timing will be real issue here. Maybe for 1080i it's really hsync as it is obscure mode that seems to not be fully supported in counters (vSyncInfoCalc), but PAL it's probably something more.

**Comment by refractionpcsx2** [comment]
I don't think the hsync counters are wrong, no, I think that it's expecting some signal which it's not getting, or checking something and not seeing the result it wants.

a lot of it does seem to be embroiled in a VIF packet (containing some GS packets, too). I could try putting that EE hack in to see if behaviour changes, but he hack at 2B9808 sounds like a similar hack to mine, so that probably "fixes" the FMV's.  Which doesn't really help us get to the root cause xD

That said, our VIF *might* be too quick, it's not impossible.

**Comment by refractionpcsx2** [comment]
Okay yeah so as expected, it's doing huge GIF packets through VIF as I observed in the decompiled code, and that's kinda what you're capturing.

This connection with DIRECT/HL to the GIF goes through a 64bit bus connection on the same frequency, so it's half the speed of the normal DMA bus which is 128bit running at 147mhz, so we should apply that backpressure to the cycle count.  Doing this (instead of your hack) also fixes the issue!

Unfortunately does not fix 10,000 bullets (which limiting hsync counting to only when vsync on "fixed")

**Comment by Goatman13** [comment]
> also fixes the issue!

Nice find!

**Comment by refractionpcsx2** [comment]
Thanks for finding the VIF thing, that really helped :D

Edit: So I made it twice as slow as I should have, and fixing that breaks it again, so that was a bit of a fail.

**Comment by Goatman13** [comment]
It may also need GS FIFO emulation in addition to 64bit interface.

<img width="601" height="169" alt="Image" src="https://github.com/user-attachments/assets/11d3ce2c-3308-4257-8101-52449fe9e28e" />

Sounds like it can additionally slowdown/stall transfer in some situations. Just guessing here.

**Comment by refractionpcsx2** [comment]
Yeah I don't think it's that,, these aren't really draw commands it's just uploading the image via VIF.

It's also just weird how the NTSC version doesn't care, but PAL is suddenly really picking about VIF uploading to the GIF being like 3x too fast? very strange.
