### ISSUE TITLE
Graphics issue: Jak 3 (USA) - SCUS97330 - Corrupted textures and excessive player shadow

### ISSUE THREAD

**Issue by Byrkoet** [PCSX2/pcsx2#168]
![1](https://cloud.githubusercontent.com/assets/1343700/3710933/ff644f0c-14b4-11e4-8e95-806dbb0e0ccb.png)
![2](https://cloud.githubusercontent.com/assets/1343700/3710935/ff64bd2a-14b4-11e4-8709-525334ca6e92.png)
![3](https://cloud.githubusercontent.com/assets/1343700/3710934/ff6484fe-14b4-11e4-9f02-6c5cde61cf41.png)

**-PCSX2 version:**
1.2.1.r5873 - compiled on Feb  3 2014

**-PCSX2 options:**
Defaults, no settings modifications affect the issue.

**-Plugins used:**
- gsdx32-sse4-r5875
- lilypad-r5875
- spu2-x-r5875
- cdvdGigaherz

**-Plugin settings:**
Tested GSdx DX9/11 hardware;
DX11 seems to make things worse by having more of an impact.
SkipDraw 1 used to remove player shadow altogether.

**-Description:**
Basically, most textures are corrupted. One great example is the right eye of most characters (also an issue in previous installments of the game).

**-How to replicate:**
Boot the game and enjoy the black-textured landscape and corrupted eyes and miscellaneous objects.

**-Last known version to work:**
Unknown, probably never worked.

**-PC specifications: CPU:**
- Intel Core i5 650 @ 4.1GHz 54 °C
- 4.00GB Dual-Channel DDR3 @ 819MHz (9-9-9-24)
- Gigabyte Technology Co., Ltd. P55-UD6 (Socket 1156) 50 °C
- 1023MB NVIDIA GeForce GTX 560 Ti (EVGA) 69 °C
- 465GB Western Digital WDC WD5000AAKX-00ERMA0 ATA Device (SATA) 45 °C

**-Other comments:**
The graphical corruption, including the missing eye(s), is also present in previous installments, including, but not limited to Jak and Daxter (SCUS97558 & SCUS97124).

**Comment by gregory38** [comment]
Could you test the shadows issue on the openGL renderer?

**Comment by charliebruce** [comment]
Latest version from git, using OpenGL, all default settings except 4x scaling, i7-4702HQ @ 2.2GHz / nVidia 765M / 8GB RAM.

![how the transporter should look](http://i.imgur.com/vATmGDM.png)
![](http://i.imgur.com/96TWLQR.jpg)
![](http://i.imgur.com/dvKtkWA.jpg)
![](http://i.imgur.com/bTTKZ5U.jpg)

Seems that the latest version has fixed some, but not all of the texture issues (water in previous screenshot fixed), but the shadow issue remains. Same in Jak 1.  

Re texture issues - eyes sometimes work perfectly, sometimes they work but look in the wrong direction (up not down), and sometimes they are either noise or black. No obvious pattern as to when the eyes do/don't work. Other mipmapping issues are still visible. Jak 1 textures all look fine apart from the eyes.

**Comment by Nobbs66** [comment]
I'll provide some GS dumps in a bit, but this is going to be a difficult issue to debug since the shadow volumes are also present in the software renderer.

**Comment by gregory38** [comment]
Increase the level of accuracy blending (likely high). It will fix the shadow issue.

**Comment by charliebruce** [comment]
Just tried all the different blending levels - none of them have any effect on the shadow issue, in Jak 1 or Jak 3.

**Comment by gregory38** [comment]
Strange. Can someone make me a gs dump of the shadow issue (disable all speedhack in PCSX2)

**Comment by Nobbs66** [comment]
i just posted the issue in the gsdx 1.0 thread on the forums

**Comment by gregory38** [comment]
You know I follow the 2 threads ;) It would have been better to post it here. Anyway I will try to give it a quick look in coming days.

**Comment by charliebruce** [comment]
http://cjb248.com/pcsx2dump/jak-shadow-glitch.zip and http://cjb248.com/pcsx2dump/jak3-shadow-glitch.zip - for Jak 1 and Jak 3.

**Comment by gregory38** [comment]
Do you confirm that shadow is broken on SW renderer too?

**Comment by gregory38** [comment]
Hum, I think I understand the issue for the shadow. I'm not sure that we can emulate it.

The bad draw call have both input texture and render target at the same address (0x3300).
The game renders triangle with basically does Alpha RT =  Alpha Fragment * Alpha Texture.
However Texture and RT is the same on the GS but not on the plugin.

So they manage to implement a kind of alpha blending of the alpha channel which is normally impossible on the GS.

**Comment by gregory38** [comment]
The best will be to allow to read the RT from the shader but it isn't easy.

Just another idea that could work.
1/ detect the effect (RT == Tex and TFX_MODULATE and only_write_alpha)
2/ Create a float texture
3/ Render with blending on with this kind of equation
* GL_FUNC_ADD
* GL_SRC_ALPHA: Alpha fragment
* GL_ZERO
4/ Convert back the RT to integer color.

We need an unclamped texture because as always alpha range from 0 to 2. However it means clamping won't be accurate. But it could be enough. Otherwise we can still do a 2 pass like the older colclip algo.

**Comment by Nobbs66** [comment]
Yes, it's broken in the software renderer as well. 

Hmm, didn't know this was such a complex issue.

**Comment by gregory38** [comment]
On gpu textures are read-only or write-only. Recent GPU (gl4) support RW texture but out-of-order with atomic. Hum I need to check if mult is supported as atomic. Or maybe replace with +/- 1, it must be close of it.

**Comment by gregory38** [comment]
Yeah no multiplication in atomic. Anyway it won't work neither the blending method above due to rounding.The game uses 127/128 factor to do a -1 and 130/128 to do a +1. Maybe we can replace the draw call with a pseudo colclip.

**Comment by gregory38** [comment]
@charliebruce 
Did you generate the above dump with VU cycle stealing enabled?

**Comment by charliebruce** [comment]
No, I don't think so - all speedhacks should have been switched off for
both of the dumps I did

**Comment by gregory38** [comment]
I pushed a hack for the shadow. Note, it is likely quite slow => `UserHacks_AutoFlush = 1`

**Comment by MrCK1** [comment]
I can test in an hour or so unless somebody else beats me to it :p

**Comment by pepiczech77** [comment]
I tested the hack and the shadows are nearly perfect. But from some camera angles they glitch out a bit.
The performance without the hack is about  30fps SW mode, 52fps HW mode.(OGL)
With the hack enabled it's about 25fps SW mode, 13fps HW mode.(OGL)
Intel Core i7-4700MQ
nVidia geforce GT 740M
Windows 8.1
![gsdx_20160908212148](https://cloud.githubusercontent.com/assets/17233252/18363780/cbc057ee-760b-11e6-9eb3-0ae27d9b3b38.png)
screen when the shadows are glitched
![gsdx_20160908213953](https://cloud.githubusercontent.com/assets/17233252/18363995/d0474fec-760c-11e6-9478-54ccb7102f1c.png)
2x native, now shadows are glitched all the time (about 2fps)

**Comment by gregory38** [comment]
Yes glitch are expected on the shadow. Except a CRC hack to replace the draw call (same issue as tri-ace game), it isn't doable with upscaling. It is already a miracle that shadows are kind of working in native resolution (due to the different rounding between integer (GS) and float (GPU) ). Potentially you could try accurate blending but it will be sluggish...

Anyway, I was expected very poor performance on the HW renderer. Perf on SW isn't too bad.

**Comment by pepiczech77** [comment]
Blending accuracy seems to have no effect. This is already great progress anyway. Thank you for working on this :) 
Do you need GS dump when it's glitched?

**Comment by gregory38** [comment]
Even on ultra (and I mean in native resolution). Ah no it might not work as the game does shits with the alpha channel.

No need for a dump. I know exactly what happen. Actually a crc might not be fast enough. Hum maybe I can test something... When I detect the bad draw call, I will try to sample from the rt instead of texture with a full barriere. I will give it a trial when I got extra motivation :)

**Comment by pepiczech77** [comment]
Native resolution and ultra. It still breaks from certain angles.
What motivation do you mean? (sorry, didn't get it)

**Comment by gregory38** [comment]
Mine ;) Devs are lazy people.

Anyway I implemented it. I don't know for the speed but it would be faster than previous hack. And it will glitch less.

However I need you game name & CRC.

**Comment by pepiczech77** [comment]
Oh, now I understand :)
Jak 3 (PAL-M7) [SCES-52460]
GSdx Lookup CRC:12804727

**Comment by gregory38** [comment]
Please test latest git (without previous hack). You need to enable accuracy blending to basic at least.

**Comment by pepiczech77** [comment]
In Jak 3 I can confirm that shadows are fine on OGL HW, but now it doesn't work in SW.


Jak X (PAL-M7) (Platinum)
Shadows seems to benefit from this hack as well
[SCES-53286] 
GSdx Lookup CRC:DF659E77
![gsdx_20160909004135](https://cloud.githubusercontent.com/assets/17233252/18369493/45ec9ba8-7626-11e6-93ea-3cf483ed69aa.png)
hack off
![gsdx_20160909004202](https://cloud.githubusercontent.com/assets/17233252/18369499/5bd64964-7626-11e6-8635-6cb6a8d6ef71.png)
hack on

**Comment by gregory38** [comment]
The CRC hack only impact the openGL HW renderer. The auto flush hacks impacts both renderer. It is likely a bad idea to enable both.
The CRC hack is a faster implementation of the auto flush hack for Jak series. By the way, could you tell me the speed impact of the CRC hack.

**Comment by pepiczech77** [comment]
I have about 47-55fps without CRC hack and about 45-52fps with the CRC hack.

**Comment by gregory38** [comment]
It is much better than previous hack, I  can't do better. Note, perf impact might be bigger if there are lots of shadows (or complex model).

For the record, I'm sorry for AMD users but perf impact will be bigger for them.

**Comment by PTKickass** [comment]
I belive you said you needed the CRC's of all Jak games that suffer from this issue, so here's a bunch of them (all of these were tested using the OGL HW renderer and high blending accuracy):

CRC:9C712FF0
![6a8fb88f592088e271d7427296276185](https://cloud.githubusercontent.com/assets/20132880/18394996/61b57510-76b4-11e6-8db7-193fe5ecc91a.jpg)

CRC:2479F4A9
![eb58f0dbfbd5a850c7b0bc9af6b42f52](https://cloud.githubusercontent.com/assets/20132880/18395050/a734e198-76b4-11e6-8575-c63a5b0dab4f.png)

CRC:DF659E77
![28c613c70d8260bcb566834296846b44](https://cloud.githubusercontent.com/assets/20132880/18395133/15731c38-76b5-11e6-80bb-f0a26c6d1e69.jpg)


Hope this helps :)

**Comment by gregory38** [comment]
I need the game name (for example jak 2). And the region too (for example Eu)

**Comment by PTKickass** [comment]
Ok, I'll say it by the same order:

Jak and Daxter: The Precursor Legacy (Europe)
Jak II - Renegade (Europe, Australia)
Jak X (Europe, Australia)

**Comment by refractionpcsx2** [comment]
jak
jak2
jakx 

then xD

**Comment by gregory38** [comment]
I pushed a new version with various CRC. Tell me if shadows are fine on the openGL renderer + accurate blending on basic.

**Comment by PTKickass** [comment]
Teste the above mentioned games with the specified settings, shadows are working fine now:
![90d4f106c50c6a61a84c5e40b58e7d12](https://cloud.githubusercontent.com/assets/20132880/18397688/3d8ec9b8-76c1-11e6-8321-1fe986de6adc.jpg)
![d1cd55a62bbf7614316414cd43407a37](https://cloud.githubusercontent.com/assets/20132880/18397699/4a1efb1c-76c1-11e6-938a-665699b2593c.png)
![6c88dbae931f56dbcb90c4e031a21f42](https://cloud.githubusercontent.com/assets/20132880/18397701/4b5380ca-76c1-11e6-8f09-295353eb837c.jpg)


Also, I can provide you one USA CRC that I have:

Jak 3 (USA) - 644CFD03
![d3ee3065e8a2552cf34959e271c05220](https://cloud.githubusercontent.com/assets/20132880/18397735/6fa53e3c-76c1-11e6-8cb8-68e611f5af20.jpg)

Also, the USA version has that weird globe on the upper left corner in all blending accuracies. Non existing in software mode btw.

**Comment by gregory38** [comment]
```
Also, the USA version has that weird globe on the upper left corner in all blending accuracies. Non existing in software mode btw.
```
You ask too much ;) Either mipmap or something wrong in the texture cache. Not for this month, working shadows are already a huge improvement.

**Comment by PTKickass** [comment]
I'm not asking, just reporting :)

**Comment by gregory38** [comment]
Actually I saw it on my gs dump. Potentially I already looked at it. If it isn't fixed it is surely a complex issue.

I added your CRC too.

By the way, who can add a gui option for the `auto flush hack`

**Comment by gregory38** [comment]
SW renderer has wrong skin color on Jak3. If you have the issue could you test the PR #1843

**Comment by FlatOutPS2** [comment]
It's fixed by PR #1843

**Comment by FlatOutPS2** [comment]
@gregory38 Jak 3 still has skin issues in Direct3D11 Hardware mode when using upscaling. Direct3D9 and OpenGL are fine, and Direct3D11 is fine on native resolution. The skin issue is basically the same as it was in Software mode, except that the markings are black. Any idea what could be causing it?

**Comment by gregory38** [comment]
Hum, hum. It could be this one.
```
void GSRendererHW::OO_Jak()
{
	// FIXME might need a CU_Jak too

```

Draw call N:
* the input texture is the CLUT content
* upscaled output is the frame buffer.

Following draw calls:
* reuse the upscaled output as CLUT table

It means that texture sampling must be 100% correct otherwise you won't have the good color. A slight rounding and you will get the neighbor texel which contains a wrong color.

**Comment by PabloDL** [comment]
i don't know if some developer already knows this, but i found that if you put the rendering in software mode, and then return to hardware mode the textures on the sand remain correctly loaded, it works every time, i don't know if its worth mentioning

**Comment by gregory38** [comment]
Yes because the bug are related to texture cache. Toggling force a reload of all textures from GS memory. If you're​ lucky it might help to fix bug. Or it will create new ones

**Comment by Traace** [comment]
I tested Jax 3 US with current nightly build (crash tag team crc) and a AMD RX 480.

Shadows issue still existing for me on opengl hw render and dx11 hw render. When I use dx11 sw render is looks fine, but its to slow

When I enable `UserHacks_AutoFlush = 1` its getting even worse. More shadow bugs, the map under the ship (intro) is just black.

Also dx11 hw render gives me 60fps ~ while opengl hw render gives 20-30 fps ~ (in every game I tested).

**Comment by yiays** [comment]
I've tested Jak 3 on build 1.5.0-3391, which should be indicitive of performance on the final 1.6.0 release (running on a Ryzen 2400G and a GTX 1060 6GB, at least)

Shadows are 90% fixed in both DX11 and OGL, Eyes are 100% fixed, however DX11 performance is abysmal, while OGL performance is fantastic. The GPU is definitely the bottleneck, I'm able to run at 4x internal resolution scale smoothly on OpenGL with my 1060, but I can barely keep up 60fps at native on DX11.

![vlcsnap-error048](https://user-images.githubusercontent.com/7791524/76742604-38184b80-67d6-11ea-9305-e0f8199d2ed4.png)

**Comment by Dreadmoth** [comment]
@yiays You can eliminate those shadow issues - use OpenGL (Hardware), set Blending Accuracy to Basic (or higher) and disable the Auto Flush hack. 
The Auto Flush hack may also be contributing to the DX11 performance issue (but is necessary for decent shadows on that renderer).

**Comment by yiays** [comment]
Yep, you're spot on. The auto flush hack causes the unusual shadows in OpenGL, and causes the terrible performance in DX11.

**Comment by lightningterror** [comment]
Maybe we can do if auto flush on, disable the blending code for jak shadows. Need to ask Greg.

**Comment by gregory38** [comment]
Auto flush will do a full GS draw by primitive. I.e. we will do a texture cache lookup and downscaling (hence the no pixel perfect rendering of the shadow).

Blending will render primitive by primitive at the GL level. So we skip the expensive texture cache. And we could work at the upscaled resolution hence the better shadow.

**Comment by giovanni9793** [comment]
@yiays I have an AMD GPU (RX 580), so I couldn't use OpenGL, so I fixed the shadow problem using Skipdraw Range at 1.

**Comment by jokoputera** [comment]
any update in this?

**Comment by jokoputera** [comment]
any update in this?

**Comment by TheTechnician27** [comment]
Update: Within the last couple months, a regression has been fixed in Jak X, and another issue which I don't believe was a regression has seemingly become more limited in scope. Both of these relate to texture corruption. Using latest dev version with D3D11 and OpenGL renderers; tested at both native resolution and 3x (1080p). 

* Regression fixed: In Jak X, the wheels had corrupted, greenish textures, especially prominent when the car is moving. Having looked at all 15 wheel types, this is no longer an issue.

* Other "fix" (can't tell, but it seems like it): there was a texture corruption issue in Jak X which corrupted the paneling textures on certain panels of certain vehicles. I can't recall exactly which parts and which vehicles, but as of right now, the only two corruptions are on the rear fender of the Howler 99 (no matter which fender style you choose) and the roof panel on the Boomer (no matter which roof panel style you choose). The software renderer eliminates both of these, but they are both present on both hardware renderers.

**Comment by SyeThunder** [comment]
> Update: Within the last couple months, a regression has been fixed in Jak X, and another issue which I don't believe was a regression has seemingly become more limited in scope. Both of these relate to texture corruption. Using latest dev version with D3D11 and OpenGL renderers; tested at both native resolution and 3x (1080p).
> 
>     * Regression fixed: In Jak X, the wheels had corrupted, greenish textures, especially prominent when the car is moving. Having looked at all 15 wheel types, this is no longer an issue.
> 
>     * Other "fix" (can't tell, but it seems like it): there was a texture corruption issue in Jak X which corrupted the paneling textures on certain panels of certain vehicles. I can't recall exactly which parts and which vehicles, but as of right now, the only two corruptions are on the rear fender of the Howler 99 (no matter which fender style you choose) and the roof panel on the Boomer (no matter which roof panel style you choose). The software renderer eliminates both of these, but they are both present on both hardware renderers.

With the 1.7.2 daily updates (1.7.2260) the green corrupted textures have resurfaced and an intermittent short freezing seems to happen on all hardware renderers

**Comment by refractionpcsx2** [comment]
I have marked this as fixed by #5580 as the textures and shadows are perfect as of that.  However the SW mode regression is still a thing, we're aware of it and I have passed it on to the people who are concerned.

**Comment by SyeThunder** [comment]
Thanks for the reply

Very coincidental timing.... I just booted up jak 3 for the first time
since posting this pretty much the minute before I got this email. Nearly
everything seems to be fixed by using vulkan and ee 130% in 1.7.24 nightly.
you guys are all doing a great job.

I still have some minor bugs if you want a detailed submission

Stephen

**Comment by refractionpcsx2** [comment]
yes, saying "Minor bugs" doesn't really helps us fix anything.

**Comment by SyeThunder** [comment]
Alright, ill get back in a few hours with details I just didnt want to load
one email with multiple different topics
