### ISSUE TITLE
Shadow of Rome - Audio cuts in and out during FMVs

### ISSUE THREAD

**Issue by Kolrath** [PCSX2/pcsx2#360]
Game: Shadow of Rome
Region: NTSC-U.  Unsure if, but assume, it occurs in other region releases.

Issue:  During FMVs the audio will start to cut in and out.  Each video starts off fine, but quickly get progressively worse.  In some long FMVs the audio will actually cut out entirely for the last portions of the FMV.

The quickest way to replicate the issue is to simply watch the opening intro that plays after the CAPCOM logo when you start the game.  By the time the video reaches the third line of dialogue "and the rule of the senate elders had begun to fray at the edges",  and is starting to show a temple on screen, the audio will start cutting in and out.  This will continue throughout the rest of the FMV.

Was there ever a working commit?  Yes

The last build with working audio was:
pcsx2-5903-windows-x86
With the notes:
"Vsync: Put it back to half slices, there seems to be games which don't like the vsync timing more accurate either way. Until i can work out why we will go back to the old half n half timing which all known games seem happy with."

The build that the audio stuttering first occurs is:
pcsx2-5904-windows-x86
With the notes:
"If you're gonna do a revert, you might as well do it properly :P If you don't want it doing properly, give it to me."

Not sure what changed between those two builds that caused the audio stuttering but 5904 seems to be the culprit.

During testing I used the "Preset 1 - Safest" settings and also tried changing the SPU-X plugin to async.  Didn't have an effect on the audio issue.  Regardless of setting changes I made build 5903 and anything before it worked fine while build 5904 and anything after it had the audio cutting in and out.

**Comment by FlatOutPS2** [comment]
http://forums.pcsx2.net/Thread-Pushed-Bug-Report-Shadow-of-Rome-NTSC-U

Bug report on the forum mentions this has been a on again, off again bug:

> extra note: I have found the build which breaks the audio after hours of testing. The version that breaks the audio is v1.3.1-1539-gc8a7a70. From then on the cut scene audio don't work properly even on the newest builds. Before that version it was working perfectly. 

So it has been fixed and regressed at least twice.

**Comment by ssakash** [comment]
> It seems like it has been fixed and regressed at least twice.

That's what happens if the timer code keeps getting reverted :P 

http://forums.pcsx2.net/Thread-vSyncInfoCalc-timing-change

**Comment by DaanDeMeyer** [comment]
I have the same problem. Tried playing around with different settings but so far nothing seems to fix the issue.

**Comment by ffrasisti** [comment]
Hey, i tried following the outdated recommendations on the wikia for the nightly and the skipdraw its says to use to fix the blur broke the game. Using half pixel offset Vertex results in still having some blurriness
the fix for me was Half Pixel Offset -> Special (Texture)
De-interlacing -> Automatic (Default)
Bilinear Filtering -> Bilinear (Smooth)
Enable Widescreen Patches (✔)  
Anti-Blur (✔)  

I am unsure whether to use "Disable Interlace Offset". I've left it on. Can someone give the game a look and update the wikia?
