### ISSUE TITLE
EE and IOP as Interpreter with EE Cache checked is broken

### ISSUE THREAD

**Issue by yxmline** [PCSX2/pcsx2#3812]
***PCSX2 version:***

[pcsx2-v1.7.0-dev-159-g4f56db9f1](https://github.com/PCSX2/pcsx2/commit/4f56db9f1844055967cd3aee8bf64613f2878515)  to [pcsx2-v1.7.0-dev-433-g7e2ccd6](https://github.com/PCSX2/pcsx2/commit/7e2ccd64e8e6049b6059141e8767037463421c33)

***PCSX2 options:***

EE and IOP as Interpreter with EE Cache checked

***Plugins used:***

default Plugins

***Description of the issue:***

EE and IOP as Interpreter with EE Cache checked is broken

***How to reproduce the issue:***

Set EE and IOP as Interpreter with EE Cache checked
no disc
boot

***Last known version to work:***

[v1.7.0-dev-156-g8816f4bf0](https://github.com/PCSX2/pcsx2/commit/8816f4bf0d3d35a2d534885ff95e00ffc12a87a5) to [v1.7.0-dev-158-g61f3258b9](https://github.com/PCSX2/pcsx2/commit/61f3258b96ab4b3d05e9072277124e1c67b24636)
EE and IOP as Interpreter without EE Cache checked is ok

***PC specifications:***
i7-3770
Window 10 
RAM 32GB
GTX 1070 TI 8GB

**Comment by refractionpcsx2** [comment]
I've fixed it on 32bit, but 64bit is completely broken still, gonna need @tellowkrinkle to look in to that.

**Comment by tellowkrinkle** [comment]
I see the patch 057791607b533c7b14b2f5b7ba4cc6c96bcb57ba for 32-bit and am confused as to how it works

If `ppf` has the top bit set (the one you're clearing with the `& 0x7fffffff`), that means it's a handler, in which case the rest is the PS2 physical address and a handler ID, not a virtual address.  Which, if you dereference it, shouldn't lead to anything on the x86 side of things unless you're (un)lucky in which case it'll lead to some random mapped memory that's being used for something else

Or at least that's what I thought would happen (I voiced confusion as to why cache emulation worked in the first place in the commit that changed this, and in the end thought that maybe it was just that only non-handler addresses were ever sent to the cache functions, in which case everything would mostly work, but if you're getting things with the top bit set then that's not the case)

**Comment by refractionpcsx2** [comment]
To be honest, I don't know what's going on xD I just copied one of the other commands to be honest, the whole PS2 memory map thing is a mystery to me and how the cache works I don't really understand either, I was kinda hoping you'd be able to work it out having delt with all the x64 stuff lol.

But yeah x64 doesn't even just crash on that, just doing anything crashes it, and it's not even setting the top bit.

**Comment by tellowkrinkle** [comment]
Yeah it seems I didn't update the cache functions to use 64-bit pointers so everything's still getting truncated

But if we're getting handlers in here, we're not going to "get lucky" and write to a random mapped region on x64 with its much larger address space (though I think I would actually consider that "unlucky", you're corrupting random memory instead of crashing

Maybe it's time to rewrite cache emulation

**Comment by refractionpcsx2** [comment]
You could be right, I just don't care enough :P But some games do need it (until we can work out a patch)

**Comment by yxmline** [comment]
x86 and x64  EE and IOP as Interpreter with EE Cache checked is working at https://github.com/PCSX2/pcsx2/pull/3841

**Comment by orbea** [comment]
@yxmline You should wait for the PR to be merged and it will close this issue automatically.
