### ISSUE TITLE
Dragons Lair 3D  and  Blood will Tell   - Distorted Graphics (unplayable)

### ISSUE THREAD

**Issue by RobAsticles** [PCSX2/pcsx2#4352]
In Dragons Laird 3D i first encountered the problem with the distorted graphics (the main character).
![PCSX2 1 7 Dragons Lair 3d](https://user-images.githubusercontent.com/82049927/113746830-0b97e000-9707-11eb-8554-e033d5b53787.jpg)
These colorful spikes also flicker all the time.

And in the game "Blood Will Tell" the main character right at the beginning is also distorted (but in another way).

PCSX2  v1.5 and v1.6 work perfectly.
with PCSX2 v1.7 the problems beginn. There has to be some changes which break these games.

**Comment by atomic83GitHub** [comment]
Booth should be fixed with the latest master, if not enable VU0 kickstart in the hacks menu

**Comment by refractionpcsx2** [comment]
Probably requires the VU0 Kickstart option under Game Fixes, yes

**Comment by RedDevilus** [comment]
Latest dev;

Dragon lair: 
    - EETimingHack # Fixes hang before going ingame.
    - VU0KickstartHack # Fixes SPS.
    
Blood Will Tell:
    - VU0KickstartHack # Fixes main character model SPS.

**Comment by refractionpcsx2** [comment]
Okay please update to the latest dev build and your problem will be solved.

In future, please make sure the problem is still present on latest master before reporting problems, otherwise we just end up chasing ghosts.
