### ISSUE TITLE
[BUG]: [Haunting Ground][PAL] Mirrors sometimes render garbage in HW, fine in SW

### ISSUE THREAD

**Issue by PolygonSlayer** [PCSX2/pcsx2#4858]
### Describe the Bug

In Haunting Ground the mirror can sometimes render garbage textures. Most apparent during cut-scenes.
Does not really hinder gameplay, but does break immersion a bit. Render fine in Software.

### Reproduction Steps

While playing the game trigger some of the cut scenes which show the mirror. One fairly early in the game, while a lot more later.

### Expected Behavior

No garbage rendered in the reflection.

### PCSX2 Revision

v1.7.0-dev-142-gef96e050f

### Operating System

Windows 8.1 (64bit)

### CPU

i7-4770T 2.50ghz

### GPU

GTX 660

### GS Settings

OpenGL 3x Native
Blending Acc. -- High
Texture Offset 300x500 (to fix bloom)

### Emulation Settings

Preset -- Balanced (happens on default too though).

### Logs & Dumps

![HauntingGround_MirrorBug](https://user-images.githubusercontent.com/44800819/135687681-a733e41c-d87e-46b1-bdc0-587bd17c5f77.png)

**Comment by Mrlinkwii** [comment]
can you please try the latest dev build

**Comment by PolygonSlayer** [comment]
Tried again on 1.7.0-dev-1841-g97b94acd86, and still same bug happening
![HauntingGround_MirrorBug_2](https://user-images.githubusercontent.com/44800819/135689949-8967d205-ca89-4481-8071-43dc7cc742dd.png)
.
[HauntingGround_mirrorBug.zip](https://github.com/PCSX2/pcsx2/files/7270283/HauntingGround_mirrorBug.zip)

Added gsdump as well, I thought I added it to previous entry, but I forgot to zip them.

**Comment by liljotik** [comment]
Also happens during the cutscene after the second boss fight. 

![1635492711325](https://user-images.githubusercontent.com/92196998/139575643-bcc469b2-026b-430a-b1f3-d3c1ff86fef7.png)

**Comment by EnekoT2001** [comment]
It still occurs on the latest build as of today. Any info about if any of the devs are looking to fix it? I feel like it's a really silly bug, other emulators like Play! don't show this bug, but they do show every other bug that PCSX2 no longer has. This game would be running perfectly if it wasn't for this, shadows, lightning, upscaling etc all work fine with some tweaking.

**Comment by EnekoT2001** [comment]
I've noticed that in new builds if I enable "preload frame data" and "texture inside rt" on hardware hacks, the reflections break even more, no reflection gets rendered at all and the corruption appears only at the very top, I tried a bunch of stuff but only this combination seems to change the reflections whatsoever, maybe it helps someone figure out what's broken better? IDK.

Link to a zip file with gs dumps for each config and my config.ini for pcsx2 qt (before enabling the preload frame data and texture inside rt stuff) https://drive.google.com/file/d/116D7ACTkS6Ry-GXffEcIBwxOD0Q8G6yx/view?usp=sharing

**Comment by dezraj** [comment]
Hello! I'm using the NTSC version of the game and also experience this issue. I have found a cut-scene in the end of the game in which the issue happens even when there is not a mirror in the room, here:
![image](https://user-images.githubusercontent.com/27839354/183313906-cf224929-296b-447f-8cc9-bf6af0817f40.png)

But there is this stylish door in the end of the corridor which seems to be made of a reflective material, so maybe this is what is triggering the glitch in this scene:

![image](https://user-images.githubusercontent.com/27839354/183313958-0e9a3665-896a-489e-a035-74768f3ba159.png)

Here's a GS dump and also a save state right before the cut scene happens (just walk one or two steps forward with the character to trigger it):
[Haunting Ground_SLUS-21075_20220807194320.zip](https://github.com/PCSX2/pcsx2/files/9277773/Haunting.Ground_SLUS-21075_20220807194320.zip)
[SLUS-21075 (901AAC09).01.zip](https://github.com/PCSX2/pcsx2/files/9277774/SLUS-21075.901AAC09.01.zip)

Hopefully a developer will look into this issue eventually and fix it in the near future.

**Comment by EnekoT2001** [comment]
> Hello! I'm using the NTSC version of the game and also experience this issue. I have found a cut-scene in the end of the game in which the issue happens even when there is not a mirror in the room, here: ![image](https://user-images.githubusercontent.com/27839354/183313906-cf224929-296b-447f-8cc9-bf6af0817f40.png)
> 
> But there is this stylish door in the end of the corridor which seems to be made of a reflective material, so maybe this is what is triggering the glitch in this scene:
> 
> ![image](https://user-images.githubusercontent.com/27839354/183313958-0e9a3665-896a-489e-a035-74768f3ba159.png)
> 
> Here's a GS dump and also a save state right before the cut scene happens (just walk one or two steps forward with the character to trigger it): [Haunting Ground_SLUS-21075_20220807194320.zip](https://github.com/PCSX2/pcsx2/files/9277773/Haunting.Ground_SLUS-21075_20220807194320.zip) [SLUS-21075 (901AAC09).01.zip](https://github.com/PCSX2/pcsx2/files/9277774/SLUS-21075.901AAC09.01.zip)
> 
> Hopefully a developer will look into this issue eventually and fix it in the near future.
> 
> PS: tested with Nightly v.1.7.3182

This also happens when a certain character becomes invisible (trying not to spoil) maybe it has to do with how the game renders transparencies? idk

**Comment by refractionpcsx2** [comment]
It broke here https://github.com/PCSX2/pcsx2/pull/5349 so maybe @iMineLink would like to take a look :)

**Comment by PolygonSlayer** [comment]
Just a note on the recent few comments.

When I made this bug initially I did not experience the bug with the glitches around the end cutscene and "flaming man". That part of the game was completely fine for me, only the mirrors where broken in HW, so not sure it's the same bug.

**Comment by dezraj** [comment]
> Just a note on the recent few comments.
> 
> When I made this bug initially I did not experience the bug with the glitches around the end cutscene and "flaming man". That part of the game was completely fine for me, only the mirrors where broken in HW, so not sure it's the same bug.

I'm sorry. I didn't mean to confuse your bug report with my additions. I just looked for "Haunting Ground" in the issue tracker before opening a new issue to avoid duplicates and found yours visually similar to the one I'm experiencing. That's why I decided to comment here. But you'd prefer I can open a new one. Thank you for your understanding.

**Comment by PolygonSlayer** [comment]
> > Just a note on the recent few comments.
> > When I made this bug initially I did not experience the bug with the glitches around the end cutscene and "flaming man". That part of the game was completely fine for me, only the mirrors where broken in HW, so not sure it's the same bug.
> 
> I'm sorry. I didn't mean to confuse your bug report with my additions. I just looked for "Haunting Ground" in the issue tracker before opening a new issue to avoid duplicates and found yours visually similar to the one I'm experiencing. That's why I decided to comment here. But if you'd prefer I can open a new one. Thank you for your understanding.

That's ok, I just wanted to make sure it's not confused with each other if they are different bugs. I could be related as well, I wouldn't know. Just wanted to point out that I did not experience the end part being bugged as you described :)
If it is a different issue it might need a new bug though, I'll leave that for the more experienced to comment on.

**Comment by iMineLink** [comment]
Ok actually I do not know if #6868 will fix all the issues reported here, but it does fix the flame guy rendering in the provided dump.

**Comment by GN876** [comment]
#6868  partially fixes the flame guy issue - There's no corruption anymore, but some parts of the screen of the door and the flaming guy will have reduced brightness, it sort of looks like it's in a transparent box. Mirrors however remain corrupted.

Mirrors look correct in latest rebase of #5534 and have no corruption issues, but there's still some corruption in the flaming guy part (not as much as latest master, and it's mostly noticeable on the lower part of the screen). This didn't happen when I used the previous build of PR5534 in April.

**Comment by iMineLink** [comment]
The flaming guy regression was introduced by #5349 which is now included (wasn't in April) in #5534 so it makes sense that you see it there now.
Such regression won't be fixed by #5534 itself because #5349 made a previously existing hack less reliable, which reliability I'm trying to improve in #6868.
I cannot reproduce in the flaming guy dump the "transparent box" effect in #6868, I guess this one needs more research.

**Comment by EnekoT2001** [comment]
well , that's progress still, im glad, because the emulation for this game in specific hasn't improved in like 3 years, happy to see some people care and are putting the work to fix these bugs

**Comment by PolygonSlayer** [comment]
Does this mean the broken mirrors are fixed too? :D

**Comment by iMineLink** [comment]
Ehm not really, #6868 just improves the flaming guy screen corruption (but adding some minor transparency issue as reported).
I guess the broken mirrors root cause is the same of the flaming guy issue but #6868 is not enough. Anyway #5534 (fixing the mirrors) is not near a mergeable state, unfortunately.

So this issue can stay open I guess.

**Comment by EnekoT2001** [comment]
Checked the new fix and the flaming man now appears ok, the reduced brightness was like that from long before too, you can test by using an old version, at least back when i played it last year it was like that. The mirrors are still broken and so is the semi-transparency of one of the characters. GS dump here for anyone interested, i believe it uses the same technique as mirrors
[HG_transparency_bug.zip](https://github.com/PCSX2/pcsx2/files/9381533/HG_transparency_bug.zip)
