### ISSUE TITLE
[BUG]: Silent Hill 2, Room 109 door texture problem.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4953]
### Describe the Bug

In the game Silent Hill 2, there is one room in the entire game where the game will produce a very weird problem which seems somewhat related to EE Timings.

In the Blue Creek section, the room 109 door entrance will display corrupted textures instead of the proper wood texture which does display properly on real hardware.

Note1 : Dobiestation/GXemu also have the problem.

Note2 : Messing with the EE cyclerate (+3 or -3) or enabling the EE Timing Hack will resolve the problem but I would not consider this a safe solution until we really know what's going on.

Note3 : the EE interpreter will flicker instead, and if you enable the ee data cache the texture will be even more corrupted.

### Reproduction Steps

Load the provided blockdump and savestate.

### Expected Behavior

The door should display a wood texture instead of the actual corrupted mess.

### PCSX2 Revision

v1.7.0-dev-1980-g52eab49359

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### Emulation Settings

MTVU and instantVU1 disabled with GameDB fixes.

### GS Window Screenshots

the bug in action:

Stock settings:

![1](https://user-images.githubusercontent.com/90222976/139336839-c00b5c76-9a22-415d-8d24-1a3a2a6213cd.png)

EE Timing hack or cyclerate to +3/-3

![2](https://user-images.githubusercontent.com/90222976/139336874-d9cbfac6-c6a5-4a64-a8e6-241901fe6734.png)

EE interpreter + EE data cache:

![3](https://user-images.githubusercontent.com/90222976/139336947-bffa74f2-b7f1-43dc-a25c-5f8f7488a1ae.png)

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/1IIN-yQOE79S5T6LM_umVAE6BRvw01ltS/view?usp=sharing

**Comment by seta-san** [comment]
Check again. A cdvd change helped certain parts of the game. Maybe this one too

**Comment by LoStraniero91** [comment]
I can't load the savestate, do you have a savegame near this part?

**Comment by gilderoylockhart01** [comment]
Sorry for the late response. I will give out my memorycard with a save just next to that room when I will be on my computer.

**Comment by gilderoylockhart01** [comment]
Here is the save:
[SH2 DOOR 109 save.zip](https://github.com/PCSX2/pcsx2/files/7738085/SH2.DOOR.109.save.zip)

**Comment by LoStraniero91** [comment]
Finally managed to test it to double check, and yes, it happens on 1.7.2353. The EE Timing Hack fixes it. I've completed the game on PCSX2 and never "caught it". Might re-test the whole game with the hack in place to see if there any issues.
![Immagine](https://user-images.githubusercontent.com/29802222/153305343-3df34706-acc9-4ddb-b220-2b49018ef91e.png)
![Immagine2](https://user-images.githubusercontent.com/29802222/153305571-c7a96f36-26d5-4c8b-b99d-05027bb07190.png)

**Comment by MrCK1** [comment]
Link to the blockdump is dead if someone is able to recheck this. Thanks.

**Comment by shinra-electric** [comment]
This is still broken on v1.7.4871
![Silent Hill 2 - Saigo no Uta_SLPM-65098_20230805162957](https://github.com/PCSX2/pcsx2/assets/50119606/500e657a-ce6d-46fe-b443-88aafed31351)

**Comment by shinra-electric** [comment]
This issue is *almost* fixed by #9777, in v1.7.4908 and later. 

The door now displays normally most of the time, but every 5~10 seconds there is a flash of the corrupted texture. 

Here is a video:
https://github.com/PCSX2/pcsx2/assets/50119606/a250e048-48b9-4cab-9974-df448c4d2f12

Tagging @refractionpcsx2 because he made the fix.

**Comment by refractionpcsx2** [comment]
Strange that should fix it, it looked like a timing problem. What happens in software mode?

**Comment by shinra-electric** [comment]
Software has the same flashing.

**Comment by refractionpcsx2** [comment]
okay then the fix above had nothing to do with it :)

But thanks for checking.
We could probably force the cycle rate in the Game DB now, which may also improve the FMV reliability.

**Comment by shinra-electric** [comment]
Ah sorry, my mistake. I was off my one. The fix was in #9773. v1.7.4906 was still broken, and it started displaying properly in v1.7.4907.

But that was also a HW fix...

**Comment by refractionpcsx2** [comment]
That one certainly makes more sense :D That was a core fix, so before the GS. 

However if that's the fix.. we might need to add a gamefix to give accurate timing on that :(  I would just do it all the time, but it's very slow to do so and most games don't care.

**Comment by Solniz** [comment]
This bug has been fixed on v2.1.46. It's working correctly on software mode, OpenGL and Vulkan (3x 1080p).
The only bug still present is the FMV freeze for a few seconds. Only happens to some of them though like the one in this room.

![Captura de ecrã 2024-07-31 210956](https://github.com/user-attachments/assets/efb3912f-77b0-4660-b82e-76ee2ee35732)

**Comment by shinra-electric** [comment]
I can confirm it's fixed on Metal as well 👍🏼
