### ISSUE TITLE
[BUG]: HDD Utility Discs boot to black screen

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5092]
### Describe the Bug

Trying to boot any HDD Utility Disc will result in a black screen. I made sure to try this after creating a PS2 hard drive image in the HDD and Network settings. This was tested PlayStation BB Navigator - Version 0.32 (Japan), HDD Utility Disc (USA), and Utility Disc Version 1.01 (Japan).

### Reproduction Steps

Try and boot any of the afformentioned discs.

### Expected Behavior

I expected the utility discs tested to boot past a black screen and function properly.

### PCSX2 Revision

PCSX2 1.7.0-0 - compiled on Dec 2 2021 (daily ppa doesnt show git number)

### Operating System

Linux (32bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Uses an iGPU, see cpu

### Logs & Dumps

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7644441/emuLog.txt)

**Comment by Florin9doi** [comment]
>That is a "MagicGate" emulation problem

It may be fixed by #4274:
![1](https://user-images.githubusercontent.com/2995486/144687783-5c171bf7-5d05-4c05-81e5-38dc980b3c6d.png)

**Comment by HeroponRikiBestest** [comment]
Unfortunately I have no way to test this, as the github builds for that pull are no longer available, and I have never successfully built PCSX2 from scratch.

**Comment by uyjulian** [comment]
Probably will never be fixed because PCSX2 doesn't want to implement MagicGate

**Comment by RedDevilus** [comment]
Ignoring implementing or not, that pull request is still broken if you look at the checks.

**Comment by Florin9doi** [comment]
> that pull request is still broken if you look at the checks.

Fixed: 
https://github.com/Florin9doi/pcsx2/commit/641266a8b069c7cfa4932f9718f943d33ceb3255

**Comment by HeroponRikiBestest** [comment]
@Florin9doi is there any chance you can update your PR to work on all operating systems? The way you updated it means it only works on windows

**Comment by maxdlpee** [comment]
A pity the devs are so concerned with non-existent legal issues that there is nothing that can be done about this.

**Comment by technica348** [comment]
> > that pull request is still broken if you look at the checks.
> 
> Fixed: [Florin9doi@641266a](https://github.com/Florin9doi/pcsx2/commit/641266a8b069c7cfa4932f9718f943d33ceb3255)

I just tried to build it and BB Navigator still crashes when I load the 0.20 version. Am I doing something wrong?

**Comment by uyjulian** [comment]
> > > that pull request is still broken if you look at the checks.
> > 
> > 
> > Fixed: [Florin9doi@641266a](https://github.com/Florin9doi/pcsx2/commit/641266a8b069c7cfa4932f9718f943d33ceb3255)
> 
> I just tried to build it and BB Navigator still crashes when I load the 0.20 version. Am I doing something wrong?

Depends on MagicGate support

**Comment by technica348** [comment]
> > > > that pull request is still broken if you look at the checks.
> > > 
> > > 
> > > Fixed: [Florin9doi@641266a](https://github.com/Florin9doi/pcsx2/commit/641266a8b069c7cfa4932f9718f943d33ceb3255)
> > 
> > 
> > I just tried to build it and BB Navigator still crashes when I load the 0.20 version. Am I doing something wrong?
> 
> Depends on MagicGate support

Yeah I am getting TLB misses so I am just going to isolate it to something with the emulator that is not yet implemented. If anyone knows how to fix this issue then that would be okay.

**Comment by refractionpcsx2** [comment]
well we don't want to poke the bear, even if it's not illegal, it feels like we're overstepping our boundaries with it.

**Comment by Sukotto-1999** [comment]
Anyway, at the moment use a fork of PCSX2 that supports partial MagicGate emulation for HDD Utility Discs. If you want MagicGate emulation in PCSX2 master, we need to pay for proper legal advice which is EXTREMELY-RISKY to do. Because doing so could GET US ARRESTED FOR EVER!!!

**Comment by dobkun** [comment]
Notably, the cryptography stuff implemented right now crashes the emulator on non-AVX2 CPUs, same behaviour as with the unofficial magicgate fork

**Comment by dobkun** [comment]
here's a crash report with more details
[cr.txt](https://github.com/user-attachments/files/16930810/cr.txt)

**Comment by dobkun** [comment]
the emulator does not produce a log
