### ISSUE TITLE
[BUG]: Gran Turismo 4 Ghost Car Transparency Issues & Behavior issues

### ISSUE THREAD

**Issue by JaCkBoston** [PCSX2/pcsx2#5133]
### Describe the Bug

In PCSX2, ghost cars are working now but they aren't 100% accurate yet. On PS2 ghost cars have a semi-transparent quality to them, while on PCSX2 they are fully opaque. They also bug out half of the time but that's a separate issue.

### Reproduction Steps

Clamping modes both Normal or Full/Extra+Preserve Sign. Test in any time trial. Happens both in Software and Hardware modes. With or without upscaling.

### Expected Behavior

Ghost cars should have semi-transparency applied to them, instead, they are fully opaque. They should also repeat the player's path through the track but instead, they flip out and get stuck all the time.

### PCSX2 Revision

1.7.2047

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 5600X

### GPU

GTX 1070

### GS Settings

![image](https://user-images.githubusercontent.com/95907526/145543092-b9243768-48e3-4b77-8fd0-65072f23cafa.png)
![image](https://user-images.githubusercontent.com/95907526/145543139-6b3dd09f-efc1-4341-9318-4afe74063266.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/95907526/145544192-cfd4d438-a4b8-4e32-8d65-0c0b345d15f1.png)
![image](https://user-images.githubusercontent.com/95907526/145544245-6e81059a-3668-492b-9176-ef757b37c27f.png)
![image](https://user-images.githubusercontent.com/95907526/145544310-9de58852-08b0-466c-9eab-0769c19104b4.png)

**Comment by MrCK1** [comment]
@JaCkBoston Can you please test again at native resolution (and all GS hacks disabled) to see if the issue still exists? Also please compare to the SW renderer and provide screenshots of both. Thanks

**Comment by JaCkBoston** [comment]
Tested at native res with all GS hacks disabled, the issue is still there. The result is the same in SW renderer.
This is HW OGL at native res with all hacks disabled:
![Screenshot_3](https://user-images.githubusercontent.com/95907526/146684600-e4d826bf-a203-4b06-a093-acc02c50f748.png)
 This is SW:
![Screenshot_2](https://user-images.githubusercontent.com/95907526/146684619-21e42476-fd38-4a5d-af92-c63a369af441.png)

This is all on version 1.7.2047. If you'd like me to test on other daily versions - feel free to ask. But I remember this same bug on previous official releases.

**Comment by JordanTheToaster** [comment]
This is fixed in #4385 

![image](https://user-images.githubusercontent.com/80843560/146686639-5c91cab0-1c27-4baa-aa4d-f96be068eb86.png)

**Comment by JaCkBoston** [comment]
> This is fixed in #4385
> 
> ![image](https://user-images.githubusercontent.com/80843560/146686639-5c91cab0-1c27-4baa-aa4d-f96be068eb86.png)

Regression then? Or guess it wasn't merged yet?

**Comment by Mrlinkwii** [comment]
@JaCkBoston  its not merged yet  , if you go to #4385  , and choose checks and you can download a pr build  and check for yourself :)

**Comment by JaCkBoston** [comment]
Alright, apologies for bumping this then :)

**Comment by F0bes** [comment]
Opening because the pr isn't in our main branch yet and the issue is still currently valid.
