### ISSUE TITLE
[BUG]: PCSX2 freezes the system when entering full-screen mode with v-sync on

### ISSUE THREAD

**Issue by dezraj** [PCSX2/pcsx2#5326]
### Describe the Bug

Hello! I'm experiencing a weird issue in which the emulator will freeze the whole system if I go full-screen with v-sync turned on (either standard or adaptive modes). I've tried it with games such as Silent Hill 2 (USA) and KoF 2003 (Japan). When the bug is triggered the only thing that still works is the mouse cursor. I can no longer interact with the system except by resetting or powering off the computer.

I'm also experiencing random crashes when opening the graphics settings. However, I don't know how the v-sync option could affect this menu.

Issue seems to have started with version pcsx2-v1.7.2187-windows-x86, which introduced the enhanced statistics display.

### Reproduction Steps

All options are default except for the vertical sync mode set to "Standard" and "Always ask when booting" for the ISO selector.

I'm using Intel UHD Graphics 630 (driver version 27.20.100.9316).

### Expected Behavior

It was supposed to work normally as it used to happen some versions before.

### PCSX2 Revision

I've tried it with pcsx2-v1.7.2187-windows-x86, pcsx2-v1.7.2190-windows-x86 and pcsx2-v1.7.2225-windows-x86 versions. I can't seem to be able to reproduce the problem with previous versions such as pcsx2-v1.7.2186-windows-x86

### Operating System

Windows 10 (64bit)

**Comment by PipoCrazy** [comment]
Are you using the x86 build for some specific reason? I´m curious

**Comment by RedDevilus** [comment]
Can't reproduce this issue.

**Comment by dezraj** [comment]
> Can't reproduce this issue.

Thank you for your testing. I suppose it should be related to the video driver also, no? It is not common that a program turn the system so unresponsive (except for the mouse cursor). If you have an Intel CPU from 6th gen (Sky-lake) or above you should be able to install the same i-GPU drivers I have.

Thanks again for your time,

**Comment by F0bes** [comment]
Can't reproduce the issue when making PCSX2 use my IGPU instead of my DGPU, x86 or x86_64.
Try downloading the latest 64 bit build [here](https://pcsx2.github.io/downloads.html)
Also, due to the fact that it seems to be a system wide issue, can you trigger the problem and then check your event viewer for driver crashes / application faults?

FWIW device manager states my driver is `INTEL (R) UHD GRAPHICS 630 30.0.101.1122`

**Comment by dezraj** [comment]
Hello! Thank you for your testing.

I've tried to trigger the bug with version pcsx2-v1.7.2234-windows-64bit-AVX2 and unfortunately got the same results.

I don't know exactly what to look for in the event viewer. I guess I would need some assistance here. But I do have some messages about Intel graphics around the moment the the bug showed, they read something like this:

"_The description for Event ID 0 from source igfxCUIService2.0.0.0 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Received Post Shell Event 1_"

Curiously by the time I opened this issue I was using display drivers version 27.20.100.9316, which is from March 2021. But I'm pretty sure I had already updated the drivers for the ones released in December 2021 (which are the latest as of today). I suspect a Windows update may have reverted the drivers to an older version. Anyway, I reinstalled the December 2021 drivers (version 30.0.101.1191) and could still reproduce the bug in PCSX2, sadly.

Thanks again for your help.

**Comment by dezraj** [comment]
Hello again! So I went and did some more testings related to this issue:

I downloaded version pcsx2-v1.7.2235-windows-64bit-AVX2 and curiously the first time I tried it it didn't freeze the emulator, but then by the second turn I was able to trigger the problem again unfortunately.

I also had the opportunity to test PCSX2 with a discrete NVIDIA desktop GPU and couldn't reproduce the problem there in any of the PCSX2 versions I had tested before, so I really suspect it's related to the Intel video drivers.

Just to remind you that issue seems to have started with version pcsx2-v1.7.2187-windows-x86, which introduced improved overlay statistics. I suppose this change has waken some kind of incompatibility with the Intel video drivers.

Anyway, I use an i5-10400 which is a desktop CPU with integrated graphics. There is no way to use a discrete GPU if I don't have one connected to the motherboard. If you use a laptop with an Intel CPU I'm not sure whether selecting "Intel GPU" in the program isolates the influence of the dedicated GPU chip or drivers. Perhaps disabling the use of the d-GPU in the BIOS could allow you to reproduce the issue hopefully? Otherwise, we would need a developer with an Intel 6th gen+ desktop CPU with integrated graphics to try this eventually.

I should be buying a discrete GPU when prices return to normal in my country. Until then I'll have to be using version pcsx2-v1.7.2186-windows-x86 to avoid this issue unfortunately.

Thank you again for your time and work.

**Comment by refractionpcsx2** [comment]
well 2187 was the QT prep part 2 PR so a LOT of things changed, including completely replacing the GS window.

**Comment by Squall-Leonhart** [comment]
There is an ongoing issue with the Intel drivers and work is underway to improve the behavior of both the windows compositor as well as Flip mode compatibility, the latest DCH driver has introduced some fixes towards the matter but not all known issues have been addressed.

**Comment by MrCK1** [comment]
@dezraj Are you still able to reproduce this on latest dev build?

**Comment by dezraj** [comment]
> @dezraj Are you still able to reproduce this on latest dev build?

Hello! Thank you for your inquiry.

As of PCSX2 version 1.7.2360-windows-64bit-AVX2, I can still reproduce the issue unfortunately, even after updating the Intel DCH GFX drivers to latest February 2022 (version 30.0.101.1340).

Out of curiosity, I went and tried PCSX2 with an old Ivy Bridge laptop with Intel HD Graphics 4000 and the emulator worked normally there, without issues (I tried the 64bit SSE4 version due to the lack of the AVX2 extension in the Ivy Bridge architecture). So the problem lies really with the Skylake+ GFX drivers.

I was thinking of filing a bug report to Intel but I doubt they have much knowledge on how PCSX2 works.

Thank you anyway for your help.

**Comment by Squall-Leonhart** [comment]
Have you globally disabled Fullscreen Optimizations, intel recently added a known issue to their list

> Running DX11 games in Fullscreen with the Windows “Fullscreen Optimization” option disabled and changing the in-game settings to full screen may result in a black screen.

**Comment by dezraj** [comment]
> Have you globally disabled Fullscreen Optimizations, intel recently added a known issue to their list
> 
> > Running DX11 games in Fullscreen with the Windows “Fullscreen Optimization” option disabled and changing the in-game settings to full screen may result in a black screen.

Thank you for your inquiry. Would this option be on the Intel Graphics Panel or in the PCSX2 settings? Either way, I haven't played with any of those as far as I remember.

By the way, I also have filed bug reports related to Intel graphics drivers and the emulators Citra and Cemu. I wonder if the upcoming Intel discrete GPUs will have these incompatibilities fixed with these programs.

**Comment by Squall-Leonhart** [comment]
It's a change that requires modification to windows registry keys,

https://www.thewindowsclub.com/enable-disable-full-screen-optimizations-windows-10

**Comment by dezraj** [comment]
> It's a change that requires modification to windows registry keys,
> 
> https://www.thewindowsclub.com/enable-disable-full-screen-optimizations-windows-10

Thank you for your assistance. I've checked that option in the PCSX2 executable and it is unchecked. So the issue definitely lies somewhere else unfortunately.

**Comment by MrCK1** [comment]
Unless there's anything else to add, this will be closed since we are unable to reproduce

**Comment by dezraj** [comment]
Hello! I am waiting a Qt release of the emulator so I can check whether the issue is present there either. Hopefully the new interface will work better with the combination of intel Skylake+ UHD graphics drivers and V-sync.
