### ISSUE TITLE
[BUG]: Jonny Moseley Mad Trix - several issues that persist in software renderer

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#6636]
### Describe the Bug

The game Jonny Moseley Mad Trix has three notable graphical inaccuracies which persist when using the software renderer but render fine on realhw.

1.  The crowd textures, and only the crowd textures, render with a gray outline with some colorful pixels not seen on realhw.  About 20 or so updates ago, this was a pink outline.  This becomes more apparent when dumping the texture and loading a custom one, where an outline of colorful pixels not seen in the custom texture appear:
![default textures](https://user-images.githubusercontent.com/58268914/179212515-bb9da926-c5ee-457f-86b0-93aeeb339aee.PNG)

![custom textures](https://user-images.githubusercontent.com/58268914/179212825-2bea1811-142f-482c-9744-9a242128c18f.PNG)

This texture does not have an extra outline on realhw.  This is the only texture in the game affected by this issue.

2.  The game's prerendered FMVs appear only on the bottom half of the screen when running with any hardware renderer, as well as rapidly flashing, making it a serious seizure risk.  When using the software renderer, it uses the top half of the screen, and stretches out along the bottom half, and does not flicker as seen below:

![FMV](https://user-images.githubusercontent.com/58268914/179213051-6dc087de-630e-4208-a77c-2a633c3515d0.PNG)

Here's what they should look like:

![FMV ps2](https://user-images.githubusercontent.com/58268914/179213126-5a785051-7027-4372-9639-427bd8afaf2b.PNG)

It's important to note that this game's FMVs did work perfectly for a very long time, then one of the early Qt builds made it just display as a black screen, and a few updates later this started.  It's been over a month and is has not been fixed yet.

3.  This one won't affect 99% of people who play the game, but it is an inaccuracy, so I need to report it.  The game has debugging functions built-in, one of which is a wireframe view.  The actual wireframe does not render properly on any renderer, even software.  This is in stark contrast to realhw where it renders perfectly, the difference is night and day:

![wireframe pcsx2](https://user-images.githubusercontent.com/58268914/179213490-c16ec077-40cf-4d97-aa36-2b9b6b61766f.PNG)

![wireframe ps2](https://user-images.githubusercontent.com/58268914/179213518-f8052cfa-667f-4b44-a619-63f3d14b513c.PNG)

### Reproduction Steps

Issue 1:  Load into any course with a crowd.

Issue 2:  Boot up the game and let the FMVs play

Issue 3:  Use the game's documented pnach cheat file, open the debug menu, and change Patch Method to Wire.

### Expected Behavior

Issue 1:  Crowd texture should not have any outline or any colorful pixels.

Issue 2:  FMVs should render properly.

Issue 3:  The wireframe view should appear as it does in the second screenshot.

### PCSX2 Revision

v1.7.3073

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i9-10900K

### GPU

NVIDIA RTX 2080 SUPER

### GS Settings

Show Overscan disabled.  Doesn't affect any of the issues above but fixes the screen being too tall.

### Logs & Dumps

GS dump for Issue 1:
[gs_20220715072528_Jonny Moseley - Mad Trix_SLUS-20229.zip](https://github.com/PCSX2/pcsx2/files/9120404/gs_20220715072528_Jonny.Moseley.-.Mad.Trix_SLUS-20229.zip)

GS dump for Issue 2:
[gs_20220715072441_Jonny Moseley - Mad Trix_SLUS-20229.zip](https://github.com/PCSX2/pcsx2/files/9120408/gs_20220715072441_Jonny.Moseley.-.Mad.Trix_SLUS-20229.zip)

GS dump for Issue 3:
[gs_20220715072541_Jonny Moseley - Mad Trix_SLUS-20229.zip](https://github.com/PCSX2/pcsx2/files/9120409/gs_20220715072541_Jonny.Moseley.-.Mad.Trix_SLUS-20229.zip)

**Comment by SlyCooperReloadCoded** [comment]
Wanted to add something to this - the way FMV videos look actually changes depending on renderer.  On Software they look like the screenshot I already posted.  On Vulkan and Direct3D12 they only take up the bottom half of the screen and flash rapidly.  On OpenGL and Direct3D11 they're duplicated, one on the top half of the screen, one of the bottom half of the screen, and the bottom one flashes rapidly.

Additionally, enabling interlacing detection prevents FMVs from rendering at all, causing them to be just a black screen.

**Comment by ps1freak26** [comment]
Here's my findings

GS Dump 1: Fixed with screen offsets

GS Dump2: Fixed with opengl and vulkan with 4x res or higher. Pink with textures in DirectX 11 and 12. Fog goes away with high blending or higher I don't know if this is more accurate or not.

GS Dump3: Black void couldn't do anything about it.

Notes: Show overscan shows more of the game. There is missing information without it.

**Comment by SlyCooperReloadCoded** [comment]
These options make no change for me, they're all still there.  Believe me I've tried everything.  The thing is, they exist in software mode, which is supposed to be hardware-accurate.

**Comment by Mrlinkwii** [comment]
can you re-post  a GS dump of that first issue   , it looks like the GS dump you posted for it  isnt the correct one :slightly_smiling_face:

**Comment by refractionpcsx2** [comment]
Videos are fine for me (even without screen offsets)

![image](https://user-images.githubusercontent.com/6278726/184904556-c689d79f-1f86-4574-84f6-1c9bb587082f.png)

The crowd issue is just something that happens if you upscale or use Anisotropic Filtering, not a bug, but a restriction in upscaling.

No clue about the debug mode.

**Comment by refractionpcsx2** [comment]
Can confirm the dump 3 with the lines works on real hardware

![image](https://user-images.githubusercontent.com/6278726/184906347-592d83af-ac49-4527-938b-a7346945bbf5.png)

**Comment by ps1freak26** [comment]
For GS dump 2 turning off anisotropic filtering did work and high blending looks more like software mode.

**Comment by SlyCooperReloadCoded** [comment]
Here's the thing - none of these GS dumps have Anisotropic Filtering enabled.  I've never had it on for this game, yet I have that problem.  Also, videos are not fine for me.  Screenshots with the different renderers:

Software with Screen Offsets disabled:
![software](https://user-images.githubusercontent.com/58268914/184939073-9a8de8a1-097a-4a4e-b9a2-b0fd2b85dd7e.PNG)

OpenGL with Screen Offsets disabled:
![opengl](https://user-images.githubusercontent.com/58268914/184939156-97786e72-cb43-4714-b22b-a24a0f6bd6c4.PNG)

Vulkan with Screen Offsets disabled:
![vulkan](https://user-images.githubusercontent.com/58268914/184939216-bfa5bcbb-ebde-41a6-b79e-9ada1ddb0418.PNG)

Vulkan with Screen Offsets enabled:
![vulkan screen offsets](https://user-images.githubusercontent.com/58268914/184939286-a781c6a8-db6f-4956-9dd6-8574b65d3f55.PNG)

Software and OpenGL with Screen Offsets enabled, still incorrect as they should fill the screen, but they're cropped weirdly here:
![softwareopengl](https://user-images.githubusercontent.com/58268914/184939324-40ad8f69-af14-4e45-ad3e-c7ec613bbfe3.PNG)

**Comment by Mrlinkwii** [comment]
> Here's the thing - none of these GS dumps have Anisotropic Filtering enabled. I've never had it on for this game, yet I have that problem. Also, videos are not fine for me. Screenshots with the different renderers:

 A gs dump save 0 config settings  , A GS dump is an export of instructions sent from the PS2 core to the "Graphics Synthesizer"

**Comment by SlyCooperReloadCoded** [comment]
Well then if the bug is caused by anisotropic filtering and upscaling, why is it happening with no anisotropic filtering or upscaling?

**Comment by refractionpcsx2** [comment]
@SlyCooperReloadCoded what version of PCSX2 are you running?

**Comment by SlyCooperReloadCoded** [comment]
1.7.3212.  I've updated many times between now and opening this issue.  What's weird is that 1.4.0/1.5.0 always rendered the FMVs correctly regardless of settings, but starting at 1.6.0 and onwards, all these issues are present.

**Comment by refractionpcsx2** [comment]
The crowd is broken when upscaling/aniso because of the way it's rendered, it's incompatible with those things.  You can try to mitigate it with upscaling hacks, but I hold no promises.

Okay well the FMV is fine for me, are you using some sort of No interlacing patch or something?

**Comment by SlyCooperReloadCoded** [comment]
The game itself is not interlaced, so I have De-Interlacing set to none.  It's been confirmed game doesn't use it at all, as without any no-interlacing patches, setting it to None causes no visual difference and no screen shaking.  That setting does affect this which is weird but the game itself is not interlaced.

**Comment by SlyCooperReloadCoded** [comment]
Okay, I set it back to Automatic and videos are still completely broken for me on all renderers

**Comment by refractionpcsx2** [comment]
Please show all your settings, I'm pretty sure this is user error. Also please check both the per game (view->properties) and global (settings) versions of your graphics settings.

**Comment by refractionpcsx2** [comment]
Why is your deinterlacing back to none?

**Comment by SlyCooperReloadCoded** [comment]
It's on automatic in the per-game config.

**Comment by refractionpcsx2** [comment]
At this point, I'd just delete your main inis and your per game configs and start again, you've just made an absolute mess of everything.

**Comment by SlyCooperReloadCoded** [comment]
Okay, I nuked all my inis and custom configs, then set everything to the settings you recommended.  FMVs are still unchanged, just a black screen.  Also, same as before, if I set Interlacing to none, they render but incorrectly.  Could this be a driver bug?

**Comment by SlyCooperReloadCoded** [comment]
I should mention that all other obviously interlaced games in my library still render their FMVs perfectly fine with De-Interlacing set to any of the options, even None.  It's only this game.  From 1.6.0 to now.

**Comment by refractionpcsx2** [comment]
Okay, but No DeInterlacing has changed since 1.6 and is mainly designed for no-interlacing patches trying to trick the system in to thinking it's full 448 height when the PS2 could only do 240 (on analogue, without the 480p mode), so it's not really designed for general use, and it automatically uses it when a no-interlacing patch is enabled.

**Comment by RedPanda4552** [comment]
Item 1 cannot reproduce (defaults, Vulkan 8x native)
![image](https://user-images.githubusercontent.com/6377490/184945897-29fd086b-99ac-4486-8e98-7d6a23cdb4e8.png)

Item 2 cannot reproduce (defaults, Vulkan 8x native)
![image](https://user-images.githubusercontent.com/6377490/184946164-7f45024f-e4d2-4783-8577-a90a9c21f437.png)

Item 3 can reproduce (defaults, Vulkan 8x native)
![image](https://user-images.githubusercontent.com/6377490/184946803-a634c872-50bc-4fb0-85ab-7103837edcdf.png)

Worth noting replaying item 3 on a PS2 does produce the wireframes, however for some reason my PS2 is making everything pink:
![PXL_20220816_175737960 - Copy](https://user-images.githubusercontent.com/6377490/184947480-07c05505-0999-4e77-a91b-9ccfd2f954de.jpg)

**Comment by JordanTheToaster** [comment]
Nothing here.

1:
![image](https://user-images.githubusercontent.com/80843560/184947889-6d0736ab-6f19-49bb-b8cb-aefaba044b25.png)


2:
![image](https://user-images.githubusercontent.com/80843560/184947928-da9fd9b7-71af-4817-9b12-e0d9362244bf.png)


3:
![image](https://user-images.githubusercontent.com/80843560/184947964-cecfe8ac-b352-4455-ae91-f7c436ce74dc.png)

**Comment by SlyCooperReloadCoded** [comment]
I did a clean driver install.  FMVs in this game and ONLY in this game are still completely bugged and unwatchable.  I genuinely don't understand what the heck could possibly be going on here.  Other people I've talked to that have tried this game have also reported FMVs being broken in the same exact way, so it's not just me, but how is it normal for so many people with the exact same settings?

**Comment by refractionpcsx2** [comment]
Are you all running custom patches or something? Have you verified your dump with redump?

Honestly, I have no answers for you, it works fine for all of us, so either your dump is bad, or you're using some patch which completely breaks the game.

**Comment by SlyCooperReloadCoded** [comment]
Everyone I've talked to before this reports the same thing as me.  I've tried redumping it and the issue persists, disc is not scratched at all.  Other people have redumped theirs and also reported no change.  I've tried it across many different comptuers with wildly different hardware and dozens upon dozens upon dozens of different settings combinations and the issue persists.  These few screenshots are the first times I've seen them work correctly!

**Comment by refractionpcsx2** [comment]
Well I dunno what to tell you, not a single one of these "everyone" people you spoke to has reported it to us before now, it used to be patched on 1.6 but is no longer required (I know because I fixed the damn game).

So, I don't have an answer for you.  Pixies did it, i guess.

**Comment by SlyCooperReloadCoded** [comment]
Interesting development.  I went back to 1.4.0 stable where multiple people have told me it works perfectly, and it no longer works there.

**Comment by SlyCooperReloadCoded** [comment]
Small update on the wireframe not rendering properly - an old issue has returned which may shed some light on it.  If you set LOD very low, then wireframe causes distant objects to become solid yellow:

![image](https://user-images.githubusercontent.com/58268914/194765196-b06d20e2-eec5-4327-877a-e972629d6c5d.png)

Another screenshot of this:

![image](https://user-images.githubusercontent.com/58268914/194765272-eea99498-c1b0-44cf-b8ba-575228941cbc.png)

Any idea what the issue could be seeing this?

**Comment by SlyCooperReloadCoded** [comment]
Wireframe still doesn't render in either software or hardware renderers as of v1.7.5500.
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/91443a4c-b139-4c6e-8dc8-0d118fed259a)

**Comment by Mrlinkwii** [comment]
I assume the wireframe is still broken?

**Comment by SlyCooperReloadCoded** [comment]
Yes, still broken.

**Comment by refractionpcsx2** [comment]
Okay so this is kind of dumb and hilarious at the same time.  So I took a look at what was going on to try and work out why we weren't drawing it and the bottom line is:

They send all the geometry as triangles with an alpha value of 128, but with anti aliasing enabled, so there are extra pixels drawn with lower alphas

they then set the alpha test to not draw any pixel which is an alpha of 128 or more.

So in summary: They are drawing wireframe using the antialias pixels!

This doesn't work on PCSX2 for 2 reasons:
1. HW mode doesn't have antialiasing, so it just completely skips the draw
2. SW mode *might* do the same, unsure, but also the anti aliasing is very janky and may not interact correctly with alpha testing, I have not tested this.

So yeah, probably not going to work in a hurry.  But just for fun, this is what it looks like if I nuke the alpha test, so it just draws everything :D

![Image](https://github.com/user-attachments/assets/e02d613b-6a1c-4a99-8ef0-ed63ce254ddd)

**Comment by SlyCooperReloadCoded** [comment]
Software rendering actually draws the gaps where the wireframe should be, but without the wireframe. Hardware doesn't draw the gaps. Real shame it's not an easy fix!

**Comment by Mrlinkwii** [comment]
![Image](https://github.com/user-attachments/assets/177c10de-80ae-49b8-ac82-79f6c73f8bae) fixed with  #12882 ([v2.3.432](https://github.com/PCSX2/pcsx2/releases/tag/v2.3.432) )

**Comment by JordanTheToaster** [comment]
Still broken in hardware.
