### ISSUE TITLE
[BUG]: Sly 3: Honor Among Thieves - VU Clamping set to "Extra + Preserve Sign" fixes a broken level but breaks shadow rendering

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#7241]
### Describe the Bug

This was brought to my attention very recently by user @Logics4.  If you have "Game Fixes" enabled in the "Advanced System" tab of any release of Sly 3, whether it's NTSC-U, PAL, or NTSC-K, character shadows will still work as expected but environment shadows will act very glitchy, rendering through other buildings, and partially popping in and out of existence.  However, if this option is disabled, both environment and character shadows act like they should.

Short video clip of shadows with "Game Fixes" enabled:

https://user-images.githubusercontent.com/58268914/196756117-8c7f65b3-9346-4aae-a0cb-f001cec7c8f9.mp4

Short video clip of shadows with "Game Fixes" disabled:

https://user-images.githubusercontent.com/58268914/196756208-2eb01821-bfda-413d-b972-a41c2fa12f39.mp4

This has been replicated across my computer and the computer of user, @Logics4.  I'll add both our CPUs and GPUs to issue.

### Reproduction Steps

1.  Edit the custom profile of any release of Sly 3.
2.  Make sure "Game Fixes" is enabled.
3.  Go ingame.

### Expected Behavior

Environment shadows should stay rendered at all times, not clip through buildings, or disappear based on camera angle.

### PCSX2 Revision

v1.7.3461

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i9-10900K (Me), AMD Ryzen 7 5800H (Logics4)

### GPU

NVIDIA RTX 2080 Super (Me), NVIDIA GeForce RTX 3060 (Logics4)

**Comment by GN876** [comment]
I tested this game last week, the camera in the level The Ancestors' Gauntlet is broken without gamefixes. VU clamping needs to be on either extra or extra + preserve sign. In my testing, extra + preserve has better performance. Seems that the rest of the game works fine with VU clamping on normal.

https://forums.pcsx2.net/Thread-Bug-Report-Sly-3-Honor-Among-Thieves-NTSC-U

**Comment by refractionpcsx2** [comment]
why didn't you check that when you added the fixes 17 days ago? https://github.com/PCSX2/pcsx2/pull/7121/files

**Comment by refractionpcsx2** [comment]
![image](https://user-images.githubusercontent.com/6278726/196764065-12e4ba4b-9b18-4799-8af4-008a3cec8c8a.png)

**Comment by Logics4** [comment]
> why didn't you check that when you added the fixes 17 days ago? #7121

So I tested a bit more, and
```yaml
SCUS-97464:
  name: "Sly 3 - Honor Among Thieves"
  region: "NTSC-U"
  compat: 5
  roundModes:
    vuRoundMode: 0 # Fixes game engine issue with bombs and ladders.
  clampModes:
    vuClampMode: 2 # Fixes bugged camera.
  gsHWFixes:
    halfPixelOffset: 2 # Fixes chromatic effect.
```
commenting out `vmClampMode` seems to fix the shadows.

**Comment by GN876** [comment]
Sadly it breaks the camera in the mission The Ancestors' Gauntlet, making it unplayable. vuClampMode needs to be on 2 or 3 for the camera in that mission to work properly.

**Comment by SlyCooperReloadCoded** [comment]
Yes, I noticed the NTSC-U ones were already there so I added them to the other regions.  I wasn't aware of any issues relating the vuClampMode but I figured it was put there for good reason.  The real fix would have to be either finding a workaround for the shadows or for the camera issues.

**Comment by refractionpcsx2** [comment]
Real hardware doesn't clamp. We clamp because we're not the real hardware, nor do we support the floats real hardware does.

**Comment by SlyCooperReloadCoded** [comment]
That's really interesting, I didn't know that.  Well VU Clamping isn't the answer for either of these then.  I'm going to mess around with settings until I find something, there's another Sly 3 issue also involving a mission-required object not appearing which was also fixed by this, I'll have plenty of ways to test.

**Comment by SlyCooperReloadCoded** [comment]
I have gone through every possible combination of settings available without modfying PCSX2's code directly, I've found nothing that fixes both.  Unless the way clamping works changes in some way, Sly 3 either:

- Is unplayable past a certain point but has correct shadow rendering
- Is fully playable but has broken shadow rendering

Some other things to note:

- If the fix for the broken level is not enabled, the level isn't always broken, but maybe 10% of the times it loads that level.  Source: I loaded the level 200 times.

- If you're in the level when it's broken and you fully reload the level, the issue will still be there, it won't follow the 10% rule above.  The issue only occurs when the game naturally transitions you to that level via the previous level.

- If you use glitches to try and traverse the level in its broken state, the game breaks down the further you go.  If you try to jump on the barrels that are there, it warps you away as if you're out of the playable area.  If you interact with the point in the middle, the entire screen goes black, HUD disappears, and the player's coordinates are set to some very large number like -30000000000000000.  Part way through the level, all 2D rendering stops entirely and framerate plummets to 10-ish FPS.  Near the halfway point of the level, all game functions that use the Circle button stop working entirely.  If you re-enable the VU Clamp fix, all the issues go away entirely, but shadow rendering stops working.

**Comment by refractionpcsx2** [comment]
The broken shadow rendering is probably the lesser evil at the moment. otherwise the game will need to be patched to adjust the calculations which break somehow, and I'm not really going to volunteer myself to do that ;)(

**Comment by SlyCooperReloadCoded** [comment]
I just checked Sly 2 and its environment shadows also break down in the same way, but that game doesn't need that option.

**Comment by Bigmac9922** [comment]
https://wiki.pcsx2.net/Sly_Cooper_and_the_Thievius_Raccoonus
https://wiki.pcsx2.net/Sly_2:_Band_of_Thieves
https://wiki.pcsx2.net/Sly_3:_Honor_Among_Thieves
All 3 wiki links seem to have incorrectly crossed out( Incorrect Line Upscaling )as fixed when the bug is still present on all three games the more you upscale the worse it gets even on all render options if you try disabling safe features it helps but does not fix the problem even on the latest builds just thought I would inform you guys about the wiki saying it is fixed just incase you want to correct it. @SlyCooperReloadCoded @refractionpcsx2

**Comment by Mrlinkwii** [comment]
@Bigmac9922  the wiki isnt fact , its mostly wrong most of the time :)

**Comment by Bigmac9922** [comment]
Ok just thought I would make you guys aware thanks for responding back so quickly.

**Comment by Jakey757** [comment]
it's not maintained by the devs, it's basically the community's responsibility to keep it up to date and accurate

**Comment by Bigmac9922** [comment]
That's understandable I just seen all three games mislabeled as fixed on this long standing bug and and thought I would just inform you guys they labeled it wrong any way thanks.

**Comment by kakashi314** [comment]
the shadows are caused by vu1, as for the broken level it is caused by vu0, the only solution is to seperate clamping from both of them.

**Comment by SlyCooperReloadCoded** [comment]
How do you know the broken level is VU0?  That would be interesting if it was true, and I never realized you could only clamp both, not one or the other.  I bet that would fix a lot of other edge cases too.

**Comment by stenzek** [comment]
Clamping/rounding the two separately is definitely something we could do. I'll throw together a PR.

**Comment by SlyCooperReloadCoded** [comment]
Semi-related, but is there a reason that EE can be overclocked but VU cannot?  I figured a VU-related PR is the best time to ask.

**Comment by stenzek** [comment]
If I remember correctly, increasing the EE cycle rate will also make those cycles available to the VUs.

**Comment by stenzek** [comment]
You can try #7707 once it builds. If it ends up fixing anything, I'll make it a gamedb option.

**Comment by refractionpcsx2** [comment]
You will need to disable game fixes for testing as it will probably force the VU clamping for both VU's via the DB on the PR currently.

**Comment by SlyCooperReloadCoded** [comment]
How do I get that?  I see the PR page, still not too familiar with how to actually get it to test it.

**Comment by refractionpcsx2** [comment]
It's not built yet, but they will appear on this page https://github.com/PCSX2/pcsx2/actions/runs/3788803092

**Comment by SlyCooperReloadCoded** [comment]
Where is Game Fixes again?  It seems to have changed location, and it's not in Advanced either.

**Comment by refractionpcsx2** [comment]
it is in advanced.

**Comment by SlyCooperReloadCoded** [comment]
So the bugged level in Sly 3, if the fix is applied, it's not consistently broken, maybe broken one out of every 10 loads, but I just loaded it roughly 30 times and didn't get it once, meanwhile shadows are fixed.  I think this fixes it, or I'm incredibly lucky, probably the former.

**Comment by kakashi314** [comment]
> So the bugged level in Sly 3, if the fix is applied, it's not consistently broken, maybe broken one out of every 10 loads, but I just loaded it roughly 30 times and didn't get it once, meanwhile shadows are fixed. I think this fixes it, or I'm incredibly lucky, probably the former.

Can you be more specific ? what fix ? VU0 or VU1 ? what clamping mode ?

**Comment by kakashi314** [comment]
I can't seem to make a pr without fucking things up.

**Comment by refractionpcsx2** [comment]
Use notepad++ and don't let it change the line endings.
