### ISSUE TITLE
[BUG]:  Pro Evolution Soccer/Winning Eleven games textures flickering (CLOSED due to "lack of developers interest").

### ISSUE THREAD

**Issue by anffss** [PCSX2/pcsx2#7328]
### Describe the Bug

All Pro Evolution Soccer/Winning Eleven games have a graphical bug on any renderer (except Software): flickering textures (kit elements, players, hairstyles, stadium elements etc.). These issue were present in ALL versions of the PCSX2, including the latest. 
In software rendering, everything is displayed correctly so it's a rendering error.

P.S. Changing the PCSX2's settings doesn't help, I checked ABSOLUTELY ALL combinations of settings including native resolution, hacks etc. I managed to hack the LOD in this games with hexediting, but even ultra high LOD values didn't help. I also tried texture replacement - the problem persists.

Screenshots (PES 2008 SLES_549.13):  
https://i.imgur.com/2WZJB1C.png
https://i.imgur.com/CRKu4JF.png

Videos (PES 2008 SLES_549.13):
https://i.imgur.com/W2du0XQ.mp4
https://i.imgur.com/ls2b45Y.mp4

### Reproduction Steps

This bug is visible when the game camera is at some distance from the player or any other object and when the camera or object is in motion. 

Renderers: Direct3D 11, Direct3D 12, OpenGL, Vulkan (in native and upscaled resolution)

I've seen this bug in almost every PES/WE game for example:

Pro Evolution Soccer 2008 (SLES_549.13)
Pro Evolution Soccer 2011 (SLES_556.36)
World Soccer Winning Eleven: Liveware Evolution 8 (SLPM_657.88)
World Soccer Winning Eleven: Liveware Evolution 9 (SLPM_660.09)

### PCSX2 Revision

v1.7.3516

### Operating System

Windows 10 (64bit)

### CPU

i5 - 10600KF

### GPU

GTX 1060

### GS Settings

Default GS settings without upscaling on any renderer.

### Emulation Settings

Default

**Comment by refractionpcsx2** [comment]
looks like Z fighting, something software can handle because it has higher precision, unfortunately we don't have that luxury right now in the hardware renderers.

**Comment by anffss** [comment]
Maybe this will still be fixed someday. I've been waiting for this for about five years and keep updating the emulator with hope, but this stupid bug is still here...

**Comment by refractionpcsx2** [comment]
unfortunately depth on PC GPU's is 32bit floating point, and it just doesn't have the precision the PS2 has (32bit integer), so we have depth problems like this showing up.  There are potentially things we can do, but it could be super slow, and might need to be reserved for ROV implementations, not sure yet, I'm not really one of the GPU guys so I can't say for certain.

I hope too it'll be fixed at some point.

**Comment by anffss** [comment]
Since november 2022, a huge number of updates have been released, but this problem is still not fixed... :(  Hopefully the developers will pay attention to this because it's not just about one game. PES/WE series has around 20 games released on PS2 platform and this problem is present in every one of them.

**Comment by Mrlinkwii** [comment]
@anffss  if you want  a quick solution use software mode

**Comment by anffss** [comment]
> @anffss if you want a quick solution use software mode

That's just genius advice, thank you. But the advice about buying a real PS2 would have been more brilliant. It would definitely solve all the problems.

**Comment by stenzek** [comment]
Considering you need to have a PS2 to dump a BIOS to legally use PCSX2, you should already have one.

As for the entitled attitude, nobody's currently working on this issue, both due to the technical limitations (depth precision), and lack of interest. You're always welcome to work on it yourself. But we're all volunteers, we work on what we feel like and are interested in, not what users dictate.

**Comment by anffss** [comment]
I didn't mean to dictate anything, I'm sorry. Maybe my words looked wrong because my English is not perfect. I'm sorry again if I looked too demanding or rude. CLOSED due to "lack of developer interest".
