### ISSUE TITLE
[BUG]: Problems in two player battle mode in Katamari Damacy (SLPS-25360)

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#8353]
### Describe the Bug

If you start two player battle mode with hw renderer, the screen goes black after loading.
(The game working in background, just without display.)
And none of Hardware fixes work.
![Katamari Damacy_SLPS-25360_20230308183938](https://user-images.githubusercontent.com/121824800/223681663-f270feca-4c5c-43c7-b5fb-966f8501f85e.png)

in SW, the game works correctly.
![Katamari Damacy_SLPS-25360_20230308183949](https://user-images.githubusercontent.com/121824800/223682774-1c6717e9-2fe0-45a8-80bc-b8295e5ac458.png)

Also, both renderer have an problem that top left screen is glitched.

### Reproduction Steps

Starts two player battle mode with HW renderer.

### PCSX2 Revision

v1.7.4198

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### Logs & Dumps

[KD_battle_GS.zip](https://github.com/PCSX2/pcsx2/files/10919769/KD_battle_GS.zip)

**Comment by SeruranBlue** [comment]
Also I realized now, if you finished an match, the some sound repeats infinitely until you exit the mode.

https://user-images.githubusercontent.com/121824800/223695508-5d96b7ec-cf55-40ec-89e6-1f59e783a046.mp4

**Comment by SeruranBlue** [comment]
Top left glitch is fixed in  v1.7.4204

**Comment by SeruranBlue** [comment]
regressed in v1.7.4207
![Katamari Damacy_SLPS-25360_20230310155659](https://user-images.githubusercontent.com/121824800/224245570-43b16358-f339-4cd8-b5e0-4b1cbb45630c.png)

**Comment by refractionpcsx2** [comment]
4206 is fine?

**Comment by SeruranBlue** [comment]
https://www.youtube.com/watch?v=djhILAbb7bA
I tested 4207.

**Comment by SeruranBlue** [comment]
here is an multi dump.
https://90.gigafile.nu/0317-s76abdf83cc347dff4b1eed1956da91ce

**Comment by refractionpcsx2** [comment]
This is mostly fixed by #9315 except the top left corner.

**Comment by seta-san** [comment]
> This is mostly fixed by #9315 except the top left corner. ![image](https://user-images.githubusercontent.com/6278726/260580413-35661f9a-786f-4966-9191-181ec60f0802.png)

should the rewrite invalidation PR close this and the problem in the top left corner move to https://github.com/PCSX2/pcsx2/issues/1318  ?

**Comment by refractionpcsx2** [comment]
Probably not, no, cos that's not the same thing.  It could still be an invalidation problem, but I'll deal with it later.

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/763b42a4-ca54-41ba-9c65-5c0a18c88656)
still an issue as of 1.7.5129

**Comment by Mrlinkwii** [comment]
![Image](https://github.com/user-attachments/assets/eecd4b4d-71f0-4c07-8472-699a3814552a)


still an issue as of v2.3.370
